Repository Recidiviz/justice-counts, pull requests merged in 2022-11, with the labels that each got.

#133 Redesigned data entry page
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Forms/NotReportedIcon.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/DataEntryHelpPage.styles.tsx
  publisher/src/components/Reports/DataEntryHelpPage.tsx
  publisher/src/components/Reports/HelperText.tsx
  publisher/src/components/Reports/PublishConfirmation.styles.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.styles.tsx
  publisher/src/components/Reports/PublishDataPanel.tsx
  publisher/src/components/Reports/ReportDataEntry.styles.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/pages/Settings.tsx
Labels: Type: Non-breaking refactor

#148 [Justice Counts] Fix data entry form bug when navigating back from publish confirm page
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
Labels: Type: Bug

#147 [Frontend][Publisher][Bug] Fix metric count in header inside review page
  publisher/src/components/Reports/PublishConfirmation.tsx
Labels: Type: Bug

#146 [Agency Dashboard] Dashboard UI scaffolding 1/n
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/Header/HeaderBar.styles.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  common/assets/download-icon.svg
  common/assets/grid-icon.svg
  common/assets/info-icon.svg
  common/assets/jc-logo-vector.png
  common/assets/menu-icon.svg
  common/assets/share-icon.svg
Labels: Type: Feature

#161 FormStore: Remove Context Validation
  publisher/src/stores/FormStore.ts
Labels: Type: Non-breaking refactor

#158 [Agency Dashboard] About Modal
  agency-dashboard/package.json
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.test.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/Header/AboutModal.styles.tsx
  agency-dashboard/src/Header/AboutModal.tsx
  agency-dashboard/src/Header/HeaderBar.styles.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  common/assets/close-icon.svg
  common/assets/grid-icon.svg
  common/assets/left-arrow-icon.svg
  common/assets/menu-icon.svg
  common/components/GlobalStyles/Palette.ts
  common/components/GlobalStyles/constants.ts
Labels: Type: Feature

#160 include FY/CY details for annual reports
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/ReportStore.test.tsx
  publisher/src/utils/dateUtils.ts
Labels: Type: Feature

#163 revert eslint rule to disable requiring react in jsx scope
  .eslintrc.js
  agency-dashboard/src/AgencyOverview.test.tsx
  agency-dashboard/src/AgencyOverview.tsx
  agency-dashboard/src/App.tsx
  agency-dashboard/src/DashboardView.test.tsx
Labels: Type: Bug

#164 display report creation error when there are overlapping report dates
  publisher/src/components/Reports/CreateReport.tsx
Labels: Type: Bug

#168 fix month off by one error for report frequency
  publisher/src/utils/dateUtils.ts
Labels: Type: Bug

#167 Race & Ethnicities: Data Entry Page (+ TabbedDisaggregations Refactor)
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/DataEntryFormComponents.tsx
Labels: Type: Non-breaking refactor

#171 add month name to all annual frequencies
  publisher/src/utils/dateUtils.ts
Labels: Type: Feature

#169 [Agency Dashboard] Responsive layout for data viz page
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/Header/HeaderBar.styles.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  common/assets/share-icon.svg
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/Legend.tsx
  common/components/GlobalStyles/constants.ts
Labels: Type: Feature

#173 Replace all instances of "report" in Publisher
  README.md
  publisher/README.md
  publisher/src/App.tsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Global/constants.ts
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/Onboarding/Onboarding.tsx
  publisher/src/components/Onboarding/OnboardingDataEntrySummary.tsx
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/components/Reports/DataEntryHelpPage.tsx
  publisher/src/components/Reports/HelperText.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/ReportStore.test.tsx
  publisher/src/stores/ReportStore.ts
  publisher/src/utils/dateUtils.ts
Labels: Type: Non-breaking refactor

#177 Race & Ethnicities (Playtesting Followup): Copy Update
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
Labels: Type: Non-breaking refactor

#178 Race & Ethnicities (Playtesting Followup): Grey Out Grid When Disaggregation Is Disabled
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
Labels: Type: Non-breaking refactor

#181 [Agency Dashboard] New dataviz controls design + metric insights placements
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/MetricInsights.tsx
Labels: Type: Feature

#172 update metric settings badges to reflect custom reporting frequency
  common/types.ts
  publisher/src/components/MetricConfiguration/MetricBox.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#179 Race & Ethnicities (Playtesting Followup): Group Races by Ethnicities in Data Entry Publish Confirmation
  publisher/src/components/Reports/PublishConfirmation.styles.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
Labels: Type: Non-breaking refactor

#182 [Fix] Settings: Metric Configuration Link
  publisher/src/components/Settings/SettingsMenu.tsx
Labels: Type: Bug

#175 Race & Ethnicities (Playtesting Followup): Remove Back To Metrics
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
Labels: Type: Non-breaking refactor

#176 Race & Ethnicities (Playtesting Followup): Make Callout Box Clickable
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
Labels: Type: Non-breaking refactor

#184 Race & Ethnicities: Replace activeMetricKey and activeSystem with URL params
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#174 Race & Ethnicities (Playtesting Followup): Debounce Saving & Send All Dimensions
  publisher/src/components/Forms/BinaryRadioButton.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor
