Repository Recidiviz/justice-counts, pull requests merged in 2022-10, with the labels that each got.

#50 Add /auth path to proxy
  publisher/src/setupProxy.js
Labels: Type: Configuration Change

#53 Data Upload: Playtesting Followup (Update Error/Warning/Success Page Copy)
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Non-breaking refactor

#54 add missing copyright header
  publisher/src/setupProxy.js
Labels: Type: Configuration Change

#60 Fix period in title
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Bug

#61 Set up common directory for sharing components between publisher + agency-dashboard
  agency-dashboard/.gitignore
  agency-dashboard/README.md
  agency-dashboard/package-lock.json
  agency-dashboard/package.json
  agency-dashboard/public/favicon.ico
  agency-dashboard/public/index.html
  agency-dashboard/public/logo192.png
  agency-dashboard/public/logo512.png
  agency-dashboard/public/manifest.json
  agency-dashboard/public/robots.txt
  agency-dashboard/src/App.css
  agency-dashboard/src/App.test.tsx
  agency-dashboard/src/App.tsx
  agency-dashboard/src/index.css
  agency-dashboard/src/index.tsx
  agency-dashboard/src/logo.svg
  agency-dashboard/src/react-app-env.d.ts
  agency-dashboard/src/reportWebVitals.ts
  agency-dashboard/src/setupTests.ts
  agency-dashboard/tsconfig.json
  agency-dashboard/yarn.lock
  common/components/SharedComponent.tsx
  common/components/index.ts
  common/package.json
  common/yarn.lock
  config-overrides.js
  package.json
  publisher/package.json
  yarn.lock
Labels: Type: Feature

#64 Settings: Metric Configuration (1/n)
  publisher/src/App.tsx
  publisher/src/components/Badge/Badge.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsView/MetricsView.styles.tsx
  publisher/src/components/MetricsView/MetricsView.tsx
  publisher/src/pages/Settings.tsx
Labels: Type: Non-breaking refactor

#59 Settings: Scaffolding
  publisher/src/App.tsx
  publisher/src/components/Badge/Badge.tsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsView/MetricsView.styles.tsx
  publisher/src/components/MetricsView/MetricsView.tsx
  publisher/src/components/Settings/AccountSettings.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/components/Settings/index.ts
  publisher/src/pages/AccountSettings.tsx
  publisher/src/pages/Settings.tsx
Labels: Type: Non-breaking refactor

#66 Settings: Metric Configuration: Metric Details & Breakdowns (2/n)
  publisher/src/components/Forms/BinaryRadioButton.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/index.ts
  publisher/src/components/MetricsView/MetricsViewMocks.ts
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/assets/gears-icon.svg
  publisher/src/pages/Settings.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Non-breaking refactor

#78 Upgrade publisher to React 18 to match agency-dashboard + move eslint config to parent directory
  .eslintrc.js
  .github/workflows/ci.yml
  agency-dashboard/package-lock.json
  agency-dashboard/package.json
  agency-dashboard/src/App.css
  agency-dashboard/src/App.test.tsx
  agency-dashboard/src/App.tsx
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/index.tsx
  agency-dashboard/src/logo.svg
  agency-dashboard/src/react-app-env.d.ts
  agency-dashboard/src/reportWebVitals.ts
  agency-dashboard/src/setupTests.ts
  common/package.json
  license-header.js
  publisher/package.json
  publisher/src/components/Auth/AuthStore.ts
  publisher/src/components/Auth/AuthWall.tsx
  publisher/src/components/Badge/Badge.tsx
  publisher/src/components/Modal/Modal.tsx
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/index.tsx
  publisher/src/stores/DatapointsStore.ts
  publisher/src/stores/ReportStore.test.tsx
  publisher/src/stores/ReportStore.ts
  publisher/src/stores/StoreProvider.tsx
  yarn.lock
Labels: Type: Feature

#85 Settings: Metric Configuration: Navigation (Table of Contents) (4/n)
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/pages/Settings.tsx
Labels: Type: Feature

#83 Settings: Metric Configuration: Definitions (3/n)
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/index.ts
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/pages/Settings.tsx
  publisher/src/shared/types.ts
Labels: Type: Feature

#98 [Frontend] Move react-scripts to devDependencies
  agency-dashboard/package.json
  publisher/package.json
  yarn.lock
Labels: Type: Configuration Change

#102 Update readme
  README.md
  agency-dashboard/README.md
Labels: Type: Configuration Change

#101 Recreate MetricsView Component for Data Visualization
  publisher/src/App.tsx
  publisher/src/components/DataViz/DatapointsView.styles.tsx
  publisher/src/components/Forms/NotReportedIcon.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
Labels: Type: Non-breaking refactor

#91 Settings: Metric Configuration: Refactor & Clean Up (5/n)
  publisher/src/App.tsx
  publisher/src/components/DataViz/DatapointsView.styles.tsx
  publisher/src/components/Forms/NotReportedIcon.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricBox.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/MetricConfiguration/index.ts
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/pages/Settings.tsx
  publisher/src/shared/types.ts
Labels: Type: Non-breaking refactor

#103 Install Jest and run jest tests in common directory & run tests on CI
  .github/workflows/ci.yml
  common/babel.config.js
  common/jest.config.js
  common/package.json
  common/setupTests.ts
  common/tsconfig.json
  yarn.lock
Labels: Type: Feature

#117 Settings: Metric Configuration: Playtesting Followups - Responsiveness (5/n)
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
Labels: Type: Non-breaking refactor

#115 Settings: Metric Configuration: Playtesting Followups - Enable Dimension Selection When Disaggregation is Off (4/n)
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
Labels: Type: Non-breaking refactor

#113 Settings: Metric Configuration: Playtesting Followups - Default Definition Hover State (3/n)
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
Labels: Type: Non-breaking refactor

#112 Settings: Metric Configuration: Playtesting Followups - Selection States (2/n)
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/assets/right-arrow.svg
Labels: Type: Non-breaking refactor

#110 Settings: Metric Configuration: Playtesting Followups - Misc. Styling Adjustments (1/n)
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/assets/right-arrow.svg
Labels: Type: Non-breaking refactor

#119 update prisons excel with new breakdowns
  publisher/public/assets/PRISONS.xlsx
Labels: Type: Non-breaking refactor

#121 Settings: Metric Configuration: Playtesting Followups - Misc. Styling Adjustments (6/n)
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/Settings/Settings.styles.tsx
Labels: Type: Non-breaking refactor

#84 Settings Feature
  common/components/DataViz/DatapointsView.styles.tsx
  common/types.ts
  publisher/src/App.tsx
  publisher/src/components/Auth/AuthWall.tsx
  publisher/src/components/Badge/Badge.tsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Forms/BinaryRadioButton.tsx
  publisher/src/components/Forms/NotReportedIcon.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricBox.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/MetricConfiguration/index.ts
  publisher/src/components/MetricsView/MetricsView.styles.tsx
  publisher/src/components/MetricsView/MetricsView.tsx
  publisher/src/components/MetricsView/MetricsViewMocks.ts
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/Settings/AccountSettings.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/components/Settings/index.ts
  publisher/src/components/assets/gears-icon.svg
  publisher/src/components/assets/right-arrow.svg
  publisher/src/pages/AccountSettings.tsx
  publisher/src/pages/Settings.tsx
  publisher/src/stores/ReportStore.ts
  publisher/yarn.lock
Labels: Type: Feature

#107 Implement Redesigned Review Page for Manual Data Entry #89
  publisher/src/components/Reports/PublishConfirmation.styles.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.styles.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
  publisher/src/components/Reports/ReportDataEntry.styles.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
Labels: Type: Non-breaking refactor

#126 [Bug] Metric Configuration: MetricBoxes Taking Up Entire Height
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
Labels: Type: Bug
