Repository Recidiviz/justice-counts, pull requests merged in 2022-12, with the labels that each got.

#191 [Justice Counts] update prisons template for bulk upload with new metrics
  publisher/public/assets/PRISONS.xlsx
Labels: Type: Non-breaking refactor

#197 [Publisher] Iowa playtesting fixes
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/ReportDataEntry.styles.tsx
Labels: Type: Bug

#194 Playtesting Followup: General Styling Fixes
  common/components/Toast/Toast.ts
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
  publisher/src/components/Onboarding/Onboarding.tsx
Labels: Type: Non-breaking refactor

#196 Playtesting Followup: Remove additional context subheader
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
Labels: Type: Non-breaking refactor

#198 Playtesting Followup: FRE Updates
  publisher/src/components/Auth/VerificationPage.tsx
  publisher/src/components/Onboarding/Onboarding.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Non-breaking refactor

#203 tweak metric title in data viz
  common/components/DataViz/DatapointsTitle.styles.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/MetricInsights.tsx
Labels: Type: Bug

#211 [Agency Dashboard] Replace placeholder metric description with api + fix metric insights disappearing
  agency-dashboard/src/AgencyOverview.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/MetricInsights.tsx
Labels: Type: Feature

#199 Custom Report Frequency
  publisher/src/components/Forms/BinaryRadioButton.tsx
  publisher/src/components/Forms/Dropdown.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/MetricConfiguration/types.ts
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/assets/calendar-icon-dark.svg
  publisher/src/components/assets/calendar-icon-light.svg
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Feature

#214 update to use new agency info in updated endpoint
  agency-dashboard/src/AgencyOverview.test.tsx
  agency-dashboard/src/DashboardView.test.tsx
  agency-dashboard/src/Header/AboutModal.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
Labels: Type: Feature

#223 fix: set starting month to July when user selects fiscal year
  publisher/src/components/MetricConfiguration/Configuration.tsx
Labels: Type: Bug

#224 simple learn more screen w live data
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/LearnMoreModal.styles.tsx
  agency-dashboard/src/LearnMoreModal.tsx
Labels: Type: Feature

#232 send user email in requests to /api/users
  publisher/src/stores/UserStore.ts
Labels: Type: Feature

#230 Supervision Metrics - Disaggregated vs Combined
  common/types.ts
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/types.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Feature

#233 [Agency Dashboard] Share Screen scaffolding
  agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx
  agency-dashboard/src/DashboardModals/LearnMoreModal.tsx
  agency-dashboard/src/DashboardModals/ShareModal.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/primitives/styles.tsx
  common/components/Toast/Toast.ts
Labels: Type: Feature

#237 [Agency Dashboard] Implement download data functionality
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  agency-dashboard/src/setupProxy.js
  common/types.ts
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/stores/FormStore.test.tsx
  publisher/src/stores/MetricConfigStore.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature

#241 Change permissions for agency settings
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
Labels: Type: Non-breaking refactor

#234 Agency metrics overview page scaffolding
  agency-dashboard/src/AgencyOverview.styles.tsx
  agency-dashboard/src/AgencyOverview.test.tsx
  agency-dashboard/src/AgencyOverview.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  agency-dashboard/src/Loading/Loading.tsx
  agency-dashboard/src/Loading/index.ts
  agency-dashboard/src/hooks/index.ts
  agency-dashboard/src/hooks/useMaxMetricBoxesInRow.ts
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/assets/graph-white.png
  common/assets/loader-sprite-horizontal.svg
Labels: Type: Non-breaking refactor

#242 [Agency Dashboard] Mobile modals for selecting metric and filters
  agency-dashboard/src/DashboardView.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/MobileFiltersModal.tsx
  common/components/DataViz/MobileModal.styles.tsx
  common/components/DataViz/MobileSelectMetricsModal.tsx
  common/types.ts
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
Labels: Type: Feature
