Repository Recidiviz/justice-counts, pull requests merged in 2022-09, with the labels that each got.

#12 [Frontend] Enforce no lint warnings
  publisher/package.json
Labels: Type: Configuration Change

#17 Rename "template" spreadsheets to "example" spreadsheets
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Non-breaking refactor

#16 [Frontend] Clear reports and datapoints state when switching agencies
  README.md
  publisher/src/components/MetricsView/MetricsView.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/DatapointsStore.ts
  publisher/src/stores/ReportStore.ts
  publisher/src/stores/StoreProvider.tsx
Labels: Type: Bug

#20 Require Pull Request Labels on all PRs
  .github/workflows/require_labels.yml
Labels: Type: Feature

#21 Small adjustments to the READMEs
  README.md
  publisher/README.md
Labels: Type: Non-breaking refactor

#19 [Frontend] Data Upload: Error/Warning Page
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Feature

#22 [Frontend] Data Entry Form Test
  publisher/src/components/Reports/DataEntryForm.test.tsx
Labels: Type: Non-breaking refactor

#23 [Frontend] Connect Review Metrics page with Data Upload API
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/types.ts
  publisher/src/components/DataViz/utils.ts
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Feature

#29 [Frontend] Update RawDatapoint type and fix positive number to expect number input
  publisher/src/components/DataUpload/types.ts
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/shared/types.ts
  publisher/src/utils/helperUtils.ts
Labels: Type: Bug

#30 [Frontend] Fix filtering metrics in review metrics page
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Bug

#32 [Frontend][Review Metrics] Review Metrics Playtesting follow-ups
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/shared/types.ts
Labels: Type: Feature

#34 [Frontend][Review Metrics] New table style to convey horizontal content
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Feature

#36 [Frontend][Review Metrics] Show old values
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Feature

#33 [Frontend] Data Upload v1: Playtesting Followups
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/SystemSelection.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/types.ts
  publisher/src/components/Loading/Loading.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#39 Make it possible to run frontend against staging backend
  publisher/.env.example
  publisher/README.md
  publisher/package.json
  publisher/src/setupProxy.js
  publisher/yarn.lock
Labels: Type: Feature

#40 [Justice Counts] change updateOnboardingStatus from PUT to PATCH
  publisher/src/stores/UserStore.ts
Labels: Type: Bug, Team: Justice Counts

#37 [Frontend] Data Upload v1: Move Uploaded Files to New Settings Page
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Forms/TextInput.tsx
  publisher/src/pages/AccountSettings.tsx
Labels: Type: Non-breaking refactor

#42 Adjust Proxy Paths
  publisher/src/setupProxy.js
Labels: Type: Non-breaking refactor

#47 Updating Supervision template
  publisher/public/assets/SUPERVISION.xlsx
Labels: Type: Non-breaking refactor

#45 Data Upload: Refactor Error/Warning/Success Page
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/types.ts
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Non-breaking refactor
