Repository Recidiviz/justice-counts, pull requests merged in 2023-10, with the labels that each got.

#985 [Publisher] Help Center: Add remaining guides, add image caption styled component, update thumbnails, add entry points
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.styled.tsx
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/HelpCenter/Guides/AccountSetupGuide.tsx
  publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx
  publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/HelpCenter/HelpCenterDirectory.tsx
  publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
  publisher/src/components/HelpCenter/LinkToPublisher.tsx
  publisher/src/components/HelpCenter/README.md
  publisher/src/components/HelpCenter/types.ts
  publisher/src/components/HelpCenter/utils.ts
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/assets/Screenshot 2023-09-29 at 6.02.22 PM.png
  publisher/src/components/assets/Screenshot 2023-09-29 at 6.04.12 PM.png
  publisher/src/components/assets/hc-account-setup-thumbnail.png
  publisher/src/components/assets/hc-add-data-thumbnail.png
  publisher/src/components/assets/hc-advanced-concepts-thumbnail.png
  publisher/src/components/assets/hc-dashboard-help-guide-thumbnail.png
  publisher/src/components/assets/hc-explore-data-thumbnail.png
Labels: Type: Non-breaking refactor

#987 Remove Cass County from denylist
  agency-dashboard/src/utils/denylist.ts
Labels: Type: Non-breaking refactor

#990 Help center content update
  publisher/src/components/HelpCenter/Guides/AccountSetupGuide.tsx
  publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx
  publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx
  publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
Labels: Type: Bug

#992 Some dashboard fixes
  agency-dashboard/src/AgencyOverview/AgencyOverview.styles.tsx
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/components/DataViz/MetricsCategoryBarChart.tsx
  common/components/DataViz/utils.ts
Labels: Type: Bug

#995 deprecate denylist file, use denylist from DB
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/utils/denylist.ts
  agency-dashboard/src/utils/index.ts
  common/types.ts
  publisher/src/components/Home/Home.test.tsx
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/stores/HomeStore.test.tsx
Labels: Type: Feature

#997 [Justice Counts] Help Center Bulk Upload copy changes
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
Labels: Type: Non-breaking refactor

#998 [Agency Dashboards] Small Fix & Clean Up
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
Labels: Type: Non-breaking refactor

#1001 [Publisher] Help Center: Self-hosted videos for Bulk Upload Guide
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/assets/HelpCenter-BulkUpload-ReviewPublish.mp4
  publisher/src/components/assets/HelpCenter-BulkUpload-Uploading.mp4
  publisher/src/react-app-env.d.ts
Labels: Type: Non-breaking refactor

#1000 [Publisher] Styling Fix in Data Viz page
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
Labels: Type: Bug, Type: Non-breaking refactor

#1003 [Security] Update @babel/core to 7.23.2 to address @babel/traverse vulnerability
  agency-dashboard/package.json
  publisher/package.json
  yarn.lock
Labels: Type: Dependency Upgrade

#1005 [Publisher] Help Center: Playtesting Followups (1/3)
  publisher/src/components/HelpCenter/Guides/AccountSetupGuide.tsx
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/assets/hc-bulkupload-breakdowncolumn-screenshot.png
  publisher/src/components/assets/hc-bulkupload-errorswarnings-screenshot.png
  publisher/src/components/assets/hc-bulkupload-superagencycolumn-screenshot.png
  publisher/src/components/assets/hc-bulkupload-supervisionsystemcolumn-screenshot.png
  publisher/src/components/assets/hc-bulkupload-yearmonthvaluecolumns-screenshot.png
Labels: Type: Non-breaking refactor

#1006 [Publisher] Help Center: Playtesting Followups (2/3)
  publisher/src/components/HelpCenter/HelpCenterDirectory.tsx
  publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
Labels: Type: Non-breaking refactor

#1009 [Publisher] Help Center: Playtesting Followups (3/3)
  publisher/src/App.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/assets/fonts/VitesseSSm-Light.otf
  publisher/src/components/assets/fonts/index.css
Labels: Type: Non-breaking refactor

#1010 [Publisher] Help Center: Playtesting Followups Quick Adjustment
  publisher/src/App.tsx
Labels: Type: Non-breaking refactor

#1012 [Publisher] Help Center: Launch
  publisher/src/App.tsx
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
Labels: Type: Non-breaking refactor

#1021 get csv for agency data from protected endpoint
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/utils/downloadHelpers.ts
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Bug

#1023 [Publisher] Help Center: Content Updates & Links to Publisher and Dashboards
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/Home/Home.tsx
  agency-dashboard/src/utils/formatting.ts
  common/utils/helperUtils.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/HelpCenter/Guides/AgencySettingsGuide.tsx
  publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx
  publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx
  publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/Guides/SuperagenciesGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Labels: Type: Non-breaking refactor

#1027 [Publisher] Help Center: Add screenshots and entry point to Dashboards from Publisher
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/HelpCenter/Guides/AgencySettingsGuide.tsx
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx
  publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx
  publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/assets/hc-agency-settings-jurisdiction-screenshot.png
  publisher/src/components/assets/hc-agency-settings-page-screenshot.png
  publisher/src/components/assets/hc-bulk-upload-page-screenshot.png
  publisher/src/components/assets/hc-dashboards-page-screenshot.png
  publisher/src/components/assets/hc-explore-data-page-screenshot.png
  publisher/src/components/assets/hc-manual-entry-page-screenshot.png
  publisher/src/components/assets/hc-manual-entry-records-screenshot.png
  publisher/src/components/assets/hc-set-up-metrics-definitions-screenshot.png
  publisher/src/components/assets/hc-set-up-metrics-page-screenshot.png
Labels: Type: Non-breaking refactor

#1026 [Agency Dashboards] Refactor of `fillTimeGapsBetweenDatapoints`
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/utils.test.ts
  common/components/DataViz/utils.ts
  common/hooks/useBarChart.ts
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/DataViz/utils.test.ts
  publisher/src/components/DataViz/utils.ts
Labels: Type: Non-breaking refactor
