Repository Recidiviz/justice-counts, pull requests merged in 2023-08, with the labels that each got.

#795 [#771][Agency Dashboard] Only allowlisted agencies should have a dashboard (all others 404)
  1
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/utils/allowlist.ts
  agency-dashboard/src/utils/env.ts
Labels: Type: Feature

#805 [#22805] linechart component story
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/.storybook/main.ts
  common/components/DataViz/CategoryOverviewLineChart.stories.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
Labels: Type: Feature

#814 Footer adjustments
  agency-dashboard/src/Footer/Footer.styles.tsx
Labels: Type: Non-breaking refactor

#809 [#771][Agency Dashboard] Only allowlisted agencies should have a dashboard (all others 404)
  1
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/stores/API.ts
  agency-dashboard/src/stores/RootStore.ts
Labels: Type: Feature

#821 Remove useEffects from AgencyOverview
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/NotFound/NotFound.tsx
Labels: Type: Bug

#819 Changes to bar charts
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/components/DataViz/BarChartComponents.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
  common/components/DataViz/Tooltip.tsx
  common/components/DataViz/types.ts
Labels: Type: Non-breaking refactor

#828 Add padding to metric name
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
Labels: Type: Non-breaking refactor

#827 Right align table numbers
  common/components/DataViz/DatapointsTableView.styles.tsx
Labels: Type: Non-breaking refactor

#808 [Agency Dashboard] Hide homepage in production
  agency-dashboard/src/Home/Home.tsx
  agency-dashboard/src/stores/API.ts
Labels: Type: Non-breaking refactor

#830 Remove homepage link from logos
  agency-dashboard/src/Header/HeaderBar.styles.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
Labels: Type: Non-breaking refactor

#834 Remove Clackamas county jail from footer
  agency-dashboard/src/Footer/Footer.tsx
Labels: Type: Non-breaking refactor

#835 [Justice Counts] Speed up Agency Dashboard home page [FE]
  agency-dashboard/src/Home/Home.tsx
  agency-dashboard/src/Home/types.ts
Labels: Type: Non-breaking refactor

#833 Fix mini charts
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
Labels: Type: Non-breaking refactor

#836 Change y-axis labels
  common/components/DataViz/MetricsCategoryBarChart.tsx
Labels: Type: Non-breaking refactor

#810 [#792] [Agency Dashboard] Part 2: Capacity and Costs Category Page (v2)
  agency-dashboard/package.json
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  agency-dashboard/src/utils/formatting.ts
  common/components/DataViz/CategoryOverviewBreakdown.styled.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
  common/components/DataViz/types.ts
  common/hooks/index.ts
  common/hooks/useBarChart.ts
  common/hooks/useLineChart.ts
  common/hooks/useLineChartLegend.ts
  common/package.json
  common/utils/dateUtils.ts
  yarn.lock
Labels: Type: Feature

#839 Fix bar chart tooltip
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/MiniBarChart.tsx
  common/components/DataViz/Tooltip.tsx
  common/components/DataViz/types.ts
Labels: Type: Bug

#838 Fix category page chart in recent mode
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/hooks/useBarChart.ts
  common/hooks/useLineChart.ts
Labels: Type: Non-breaking refactor

#844 Fix bounce back bug in publisher configuration page
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/pages/NotFound.tsx
Labels: Type: Bug

#854 [Justice Counts] System replace underscore with space
  publisher/src/components/Home/Home.tsx
Labels: Type: Bug

#855 [Bug] DataEntryReview sometimes crashes when metricDisplayNames is initially undefined
  publisher/src/components/Reports/DataEntryReview.tsx
Labels: Type: Bug

#857 [Publisher] Styling fix for long system names
  publisher/src/components/Home/Home.styled.tsx
Labels: Type: Bug

#852 Remove category title if category metrics have no data
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
Labels: Type: Non-breaking refactor

#845 [Justice Counts] 1.4 Refactoring frontend to call `get_bulk_upload_template` A…
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature, Type: Non-breaking refactor

#862 [Publisher] Remove HeaderBar label from standalone errors/warnings page
  publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
Labels: Type: Non-breaking refactor

#863 Toggle "Down for Maintenance" page with boolean flag
  publisher/src/App.tsx
Labels: Type: Feature

#860 [DO NOT MERGE] Data Viz Bounce Back Bug Proposal
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Settings/hooks.ts
Labels: Type: Non-breaking refactor

#853 Fix data page bug
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Settings/hooks.ts
Labels: Type: Bug

#871 [#866] Remove footer from Agency Dashboard
  agency-dashboard/src/Footer/Footer.tsx
Labels: Type: Feature

#879 Allowing agencies of any system to have a Capacity and Costs dashboard (as long as they are allowlisted)
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
Labels: Type: Feature

#882 update allowlist
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/utils/allowlist.ts
Labels: Type: Feature

#883 [Proposal][Agency Dashboards] Move allowlist logic up a level to a "wrapper" component
  agency-dashboard/src/AgencyOverview/AgencyOverview.test.tsx
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/App.tsx
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/Protected/index.ts
  agency-dashboard/src/utils/index.ts
Labels: Type: Non-breaking refactor

#869 Publisher nits
  common/assets/gear-settings-icon.svg
  common/components/Badge/Badge.tsx
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsTableView.tsx
  common/components/DataViz/utils.ts
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Home/Home.styled.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/primitives/index.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#886 Remove "report" word from `common` repo
  agency-dashboard/src/utils/formatting.ts
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
  common/components/DataViz/Tooltip.tsx
Labels: Type: Non-breaking refactor

#880 [#22950] [Agency Dashboard] breakdown chart updates
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  agency-dashboard/src/Header/HeaderBar.styles.tsx
  agency-dashboard/src/utils/formatting.ts
  common/components/DataViz/CategoryOverviewBreakdown.styles.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/types.ts
  common/components/DataViz/utils.ts
  common/utils/dateUtils.ts
Labels: Type: Feature

#885 [#22940] Fix Iowa DOC error
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
Labels: Type: Bug

#888 [Agency Dashboards] Wrap CategoryOverview and DashboardView within the <Protected> component to enforce the allowlist
  agency-dashboard/src/App.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
Labels: Type: Non-breaking refactor

#846 [Publisher] Refactor Homepage/Task Card logic to newly implemented mobX HomeStore
  common/types.ts
  common/utils/dateUtils.ts
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/helpers.ts
  publisher/src/components/Home/index.ts
  publisher/src/components/Home/types.ts
  publisher/src/stores/HomeStore.ts
  publisher/src/stores/ReportStore.ts
  publisher/src/stores/RootStore.ts
  publisher/src/stores/index.ts
Labels: Type: Non-breaking refactor

#856 [Publisher] Home + HomeStore: Tests
  common/types.ts
  publisher/src/components/Home/Home.test.tsx
  publisher/src/mocks/HomeMocksHelpers.ts
  publisher/src/stores/FormStore.ts
  publisher/src/stores/HomeStore.test.tsx
Labels: Type: Non-breaking refactor

#891 [Bug][Agency Dashboard] Add checks additional checks for data to prevent crashing
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
Labels: Type: Bug

#865 Superagencies: Add pinned Upload Data task card in homepage for superagencies
  common/types.ts
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/components/Home/Home.test.tsx
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/types.ts
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/stores/HomeStore.test.tsx
  publisher/src/stores/HomeStore.ts
  publisher/src/stores/UserStore.ts
Labels: Type: Non-breaking refactor

#900 [Agency Dashboard] Use same source of truth/calc for list of metrics between AgencyOverview and CategoryOverview
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  agency-dashboard/src/Protected/Protected.tsx
Labels: Type: Non-breaking refactor

#902 [Bug][Publisher] Fix Explore Data crash when agency has no enabled metrics
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Bug

#893 [Agency Dashboard][Refactor] AgencyOverview & General Refactor + Cleanup
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/Header/HeaderBar.tsx
  agency-dashboard/src/Home/Home.tsx
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/stores/API.ts
  agency-dashboard/src/stores/AgencyDataStore.ts
  agency-dashboard/src/utils/formatting.ts
  agency-dashboard/src/utils/index.ts
  agency-dashboard/src/utils/networking.ts
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/utils.ts
  common/utils/dateUtils.ts
  publisher/src/components/DataViz/utils.test.ts
  publisher/src/components/DataViz/utils.ts
Labels: Type: Non-breaking refactor

#867 Superagencies: Add copy for non-superagency systems within Metric Settings
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/primitives/index.tsx
Labels: Type: Non-breaking refactor

#868 Superagencies: Only show superagency system data and add copy explaining how to view child agency data
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/primitives/index.tsx
Labels: Type: Non-breaking refactor

#908 [Agency Dashboard] Change ALLOW_LIST to DENY_LIST
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/utils/allowlist.ts
  agency-dashboard/src/utils/denylist.ts
  agency-dashboard/src/utils/index.ts
Labels: Type: Non-breaking refactor

#911 add button for single page upload customized template
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature
