Repository Recidiviz/justice-counts, pull requests merged in 2023-03, with the labels that each got.

#449 Follow-up team management responsive design adjustments
  common/components/GlobalStyles/constants.ts
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/Settings/AccountSettings.styles.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/Settings.styles.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#452 Follow up general design
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/GlobalStyles/constants.ts
  publisher/src/components/Footer/Footer.styles.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/assets/dropdown-arrow.svg
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#458 Remove empty scrollbars from publisher app
  common/components/DataViz/DatapointsTableView.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/Settings.styles.tsx
Labels: Type: Non-breaking refactor

#461 Sticky headers for responsive view
  common/components/DataViz/DatapointsView.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
Labels: Type: Non-breaking refactor

#460 Refactor Metric Configuration to better mesh responsiveness changes with Guidance's metric config UI updates
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
Labels: Type: Non-breaking refactor

#456 Guidance: Playtesting II Followups
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
Labels: Type: Non-breaking refactor

#464 [Justice Counts] new bulk upload templates with better column widths
  publisher/public/assets/COURTS_AND_PRETRIAL.xlsx
  publisher/public/assets/DEFENSE.xlsx
  publisher/public/assets/JAILS.xlsx
  publisher/public/assets/LAW_ENFORCEMENT.xlsx
  publisher/public/assets/PRISONS.xlsx
  publisher/public/assets/PROSECUTION.xlsx
  publisher/public/assets/SUPERVISION.xlsx
Labels: Type: Non-breaking refactor

#462 Small text changes
  agency-dashboard/src/DashboardModals/LearnMoreModal.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
Labels: Type: Non-breaking refactor

#463 Remove empty scrollbars from all repos
  agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx
  agency-dashboard/src/Header/AboutModal.styles.tsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Onboarding/OnboardingDataEntrySummary.tsx
  publisher/src/components/Reports/DataEntryHelpPage.styles.tsx
  publisher/src/components/Reports/HelperText.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
Labels: Type: Non-breaking refactor

#469 [Bug] Update the FE names for races and ethnicities to match what the backend sends
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesGridStates.ts
  publisher/src/components/MetricConfiguration/types.ts
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Bug

#465 Guidance: Update Metric Configuration overview list for multi-system agencies & agencies with subsystems
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/types.ts
  publisher/src/stores/GuidanceStore.ts
Labels: Type: Non-breaking refactor

#473 Guidance: Playtesting II Followups - Metric Configuration Toast Checklist
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#479 Metric Configuration: Adjustment for long dimension names
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
Labels: Type: Non-breaking refactor

#485 Metric Configuration Overview: show "Annually" instead of "Annual
  publisher/src/components/MetricConfiguration/MetricBox.tsx
Labels: Type: Non-breaking refactor

#486 Re-center loader in Data Upload component
  publisher/src/components/DataUpload/DataUpload.styles.tsx
Labels: Type: Non-breaking refactor

#471 Follow up responsive fixes for metric configuration
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/DimensionContexts.tsx
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicities.styles.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
Labels: Type: Non-breaking refactor

#487 Multiple Includes/Excludes
  agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx
  agency-dashboard/src/DashboardModals/LearnMoreModal.tsx
  common/types.ts
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/stores/GuidanceStore.test.tsx
  publisher/src/stores/GuidanceStore.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#489 [Bug] Fix empty bar charts showing '0 auto' in the x-axis
  common/package.json
  publisher/package.json
  yarn.lock
Labels: Type: Bug

#490 Fix choosing disabled metric after system change
  publisher/src/components/MetricConfiguration/MetricsView.tsx
Labels: Type: Bug

#492 Update sorting logic for DataViz legend
  common/components/DataViz/utils.ts
Labels: Type: Bug, Type: Non-breaking refactor

#497 Guidance: Gate feature for non-JC Admins
  publisher/src/stores/GuidanceStore.ts
Labels: Type: Non-breaking refactor

#488 Records page UI refresh
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/Global/constants.ts
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Reports/RemoveRecordsModal.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#504 Guidance: adjust the step-completion logic for ADD DATA step
  publisher/src/components/Guidance/Guidance.tsx
Labels: Type: Non-breaking refactor

#501 Bulk Publishing: API
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Non-breaking refactor

#517 Remove permissions for agency dropdown menu
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#516 [Bulk Upload] Adjust title / definition of a successfully saved metric
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Non-breaking refactor

#533 Fix selection behavior for "All records" and "Not started" tabs
  publisher/src/pages/Reports.tsx
Labels: Type: Bug

#518 [Bulk Upload] Grey out disabled metrics
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/types.ts
Labels: Type: Non-breaking refactor

#537 Fix agency settings responsiveness
  publisher/src/components/Settings/AgencySettings.styles.tsx
Labels: Type: Bug

#536 Extend disabled behavior for bulk actions
  publisher/src/pages/Reports.tsx
Labels: Type: Feature

#538 [Justice Counts] Metrics Not Uploaded section in bulk upload review page
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/types.ts
Labels: Type: Non-breaking refactor

#553 Metric Config: Update copy for confirming breakdown availability
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
Labels: Type: Non-breaking refactor

#552 Allow JC Admins to access Records / Bulk Upload during Guidance
  publisher/src/components/Menu/Menu.tsx
  publisher/src/router/Router.tsx
Labels: Type: Non-breaking refactor

#551 Update app title, metadata and favicons
  publisher/public/android-chrome-192x192.png
  publisher/public/android-chrome-256x256.png
  publisher/public/android-chrome-512x512.png
  publisher/public/apple-touch-icon.png
  publisher/public/favicon-16x16.png
  publisher/public/favicon-32x32.png
  publisher/public/favicon.ico
  publisher/public/index.html
  publisher/public/og-jcpublisher.png
Labels: Type: Non-breaking refactor
