Repository Recidiviz/justice-counts, pull requests merged in 2023-12, with the labels that each got.

#1099 [Justice Counts] Add "Define Metric ->" link to all aggregate metrics in metric configuration
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#1084 [Publisher] Admin Panel: Agency Provisioning - Styling & Misc. Adjustments (1/n)
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/InteractiveSearchList.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
Labels: Type: Non-breaking refactor

#1085 [Publisher] Admin Panel: Agency Provisioning - Store Updates (2/n)
  common/types.ts
  common/utils/helperUtils.ts
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/stores/AdminPanelStore.test.tsx
  publisher/src/stores/AdminPanelStore.ts
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1087 [Publisher] Admin Panel: Agency Provisioning - Create/Edit Agency Information (4/n)
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
Labels: Type: Feature

#1089 [Publisher] Admin Panel: Admin Panel Role & Publisher Entry Point
  publisher/src/App.tsx
  publisher/src/components/Auth/AuthStore.ts
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Feature

#1088 [Publisher] Admin Panel: Agency Provisioning - Team Members (5/n)
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1100 [Publisher] Admin Panel: Agency Provisioning - Superagency System Addition/Removal (6/n)
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/types.ts
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/SystemSelection.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Home/types.ts
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/types.ts
  publisher/src/components/Settings/utils.ts
  publisher/src/stores/AdminPanelStore.ts
  publisher/src/stores/AgencyStore.ts
  publisher/src/stores/HomeStore.ts
  publisher/src/stores/MetricConfigStore.tsx
  publisher/src/stores/ReportStore.ts
  publisher/src/utils/helperUtils.ts
Labels: Type: Feature

#1102 include `user_account_id` in request when creating new users from the admin panel
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1103 [Publisher] Admin Panel: Create User/Agency from opposite flows
  common/components/DelayedRender/DelayedRender.tsx
  common/components/DelayedRender/index.ts
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AdminPanel.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/InteractiveSearchList.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1105 [Publisher] Admin Panel: Clean Up
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1106 [Publisher] Admin Panel: Handle auto-adding all agencies to newly created CSG/Recidiviz users & include Recidiviz users when auto-adding team members when creating new agency
  common/utils/helperUtils.ts
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1110 [Bug][Publisher] Admin Panel: Playtesting Followup - Fix crash edgecase when username is a string full of spaces
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/Settings/AccountSettings.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Bug

#1111 [Publisher] Admin Panel: Playtesting Followup - Remove "(required)" from state search box in Agency Provisioning modal
  common/components/Toast/Toast.ts
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Non-breaking refactor

#1112 [Publisher] Admin Panel: Playtesting Followup - Fix Select All users bug in Agency Provisioning modal
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Bug

#1113 [Publisher] Admin Panel: Playtesting Followup - Refetch users and agencies when a change has been made to a superagency/child agency selection
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1118 [Publisher] Admin Panel: Playtesting Followup - Add agency name header for single agency users
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#1121 [Publisher][Bug] Explore Data: Fix broken "Go to Metric Settings" link
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Bug

#1119 [Publisher] Admin Panel: Playtesting Followup - Add indicator on the agency overview cards for child agencies
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/stores/AdminPanelStore.test.tsx
Labels: Type: Non-breaking refactor

#1120 [Publisher] Admin Panel: Quick UI adjustment of add agencies list position
  publisher/src/components/AdminPanel/UserProvisioning.tsx
Labels: Type: Non-breaking refactor

#1116 [Publisher] Admin Panel: Playtesting Followup - Require at least one sector selection when creating/editing agencies
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Non-breaking refactor

#1117 [Publisher] Admin Panel: Playtesting Followup - Empty search input in overview pages after saving & refactor filtering logic
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1124 [Publisher] Admin Panel: Enable admin panel in production environment
  publisher/src/App.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#1122 [Publisher] Add Sentry Logging
  publisher/package.json
  publisher/src/components/Auth/AuthStore.ts
  publisher/src/index.tsx
  yarn.lock
Labels: Type: Feature

#1123 [Publisher] Prevent agencies from being able to have supervisions metrics that are both combined and disaggregated
  common/components/RadioButton/RadioButtonsWrapper.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor
