Repository Recidiviz/justice-counts, pull requests merged in 2023-01, with the labels that each got.

#270 Agency Dashboard playtesting followups
  agency-dashboard/src/AgencyOverview.tsx
  agency-dashboard/src/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView.tsx
  agency-dashboard/src/index.tsx
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/Legend.tsx
  common/components/DataViz/MobileSelectMetricsModal.tsx
  common/components/DataViz/Tooltip.tsx
Labels: Type: Bug

#275 update data table labels with custom reporting frequency
  publisher/src/components/MetricConfiguration/MetricsView.tsx
Labels: Type: Bug

#277 [Justice Counts] Replace hardcoded email addresses with emails from the DB
  common/types.ts
  publisher/src/components/Settings/AgencySettings.tsx
Labels: Type: Feature

#276 Share data viz with filters applied in the url params
  agency-dashboard/src/DashboardModals/DashboardModal.styles.tsx
  agency-dashboard/src/DashboardModals/ShareModal.tsx
  agency-dashboard/src/DashboardView.tsx
  common/assets/status-check-icon.png
  common/stores/DataVizStore.ts
  common/types.ts
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/Forms/TextInput.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Feature

#283 send email_verified when retrieving user permissions
  publisher/src/stores/UserStore.ts
Labels: Type: Feature

#292 Small refactor to user permissions
  common/types.ts
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Configuration Change

#303 Fix download template issue due to routing change
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Bug

#299 [Admin Permissions] Only allow most agency settings if user is admin
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
Labels: Type: Feature

#311 Fix link to metric config in data entry form, fix back button on metric config
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Settings/hooks.ts
Labels: Type: Bug

#302 Change label from Annual to Annually in Metric Config
  publisher/src/components/MetricConfiguration/Configuration.tsx
Labels: Type: Non-breaking refactor

#318 Lower case url params in metric config
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Settings/hooks.ts
  publisher/src/components/Settings/utils.ts
Labels: Type: Feature

#307 [Frontend] Allow agency admins to create reports
  publisher/src/pages/Reports.tsx
Labels: Type: Feature

#304 Refactor toast component
  agency-dashboard/src/AgencyOverview.tsx
  agency-dashboard/src/DashboardModals/ShareModal.tsx
  agency-dashboard/src/DashboardView.tsx
  common/components/Toast/Toast.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Onboarding/Onboarding.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/stores/API.ts
  publisher/src/stores/AgencyStore.ts
  publisher/src/stores/MetricConfigStore.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Non-breaking refactor

#312 Refactor metric configuration callbacks (remove them from render)
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/ContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
Labels: Type: Non-breaking refactor

#308 Add Additional Context field for All "Other" dimensions
  common/types.ts
  publisher/src/components/MetricConfiguration/DimensionContexts.tsx
  publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/index.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#327 [Bug] Prevent rendering of metric level context component when the context array is empty
  publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
Labels: Type: Bug

#319 UI to display badge next to users that are admins
  publisher/package.json
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/assets/agency-admin.svg
  publisher/src/components/assets/recidiviz-admin.svg
  publisher/src/components/primitives/index.tsx
  publisher/src/index.tsx
  publisher/src/pages/Reports.tsx
  yarn.lock
Labels: Type: Feature

#261 Guidance: mobX Data Store
  publisher/src/App.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/index.ts
  publisher/src/components/Guidance/types.ts
  publisher/src/router/Router.tsx
  publisher/src/stores/GuidanceStore.ts
  publisher/src/stores/RootStore.ts
Labels: Type: Feature

#262 Guidance: Scaffolding
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/GuidanceHeader.tsx
  publisher/src/components/Guidance/index.ts
  publisher/src/components/Guidance/types.ts
  publisher/src/components/Header/Header.styles.tsx
  publisher/src/router/Router.tsx
Labels: Type: Feature

#263 Guidance: Setup Your Agency
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/types.ts
Labels: Type: Feature

#266 Guidance: Add Data
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/GuidanceHeader.tsx
  publisher/src/router/Router.tsx
Labels: Type: Feature

#269 Guidance: Publish Data
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/GuidanceHeader.tsx
  publisher/src/components/Reports/PublishConfirmation.tsx
  publisher/src/components/Reports/ReviewReportDataEntry.tsx
  publisher/src/router/Router.tsx
Labels: Type: Feature

#333 Follow up updated designs for agency settings
  common/assets/add-icon.svg
  common/assets/black-check-icon.svg
  common/assets/edit-row-icon.png
  common/assets/remove-warning-icon.png
  common/components/GlobalStyles/Palette.ts
  common/components/Toast/Toast.ts
  common/types.ts
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsConfirmModal.tsx
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagementConfirmModal.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/components/Settings/utils.ts
  publisher/src/components/assets/no-background-check-icon.svg
  publisher/src/pages/Settings.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#341 [Fix] Adjustments to "Technical Definitions are not available for this metric yet." logic
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
Labels: Type: Non-breaking refactor

#343 New frontend handling of supervision disaggregations
  common/types.ts
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
Labels: Type: Feature

#345 Sort Agency dropdown alphabetically by name
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#352 Actually save draft with "Save as Draft" button
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Bug

#351 [Justice Counts] updated Prisons bulk upload template
  publisher/public/assets/PRISONS.xlsx
Labels: Type: Non-breaking refactor

#347 Hook team management api with frontend
  common/types.ts
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature
