Repository Recidiviz/justice-counts, pull requests merged in 2023-09, with the labels that each got.

#912 [Test] Add FormStore test to cover buggy line addition in DataEntryReview
  publisher/src/stores/FormStore.test.tsx
Labels: Type: Non-breaking refactor

#913 Fix metrics list validation in Publish Review page when coming from a publish task card in the Home page
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/stores/FormStore.ts
Labels: Type: Non-breaking refactor

#914 Add typeahead search in agency dropdown menu
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  common/components/GlobalStyles/Palette.ts
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#922 Data Viz: Change "Year-to-Year" text to "Percent Change"
  common/components/DataViz/MetricInsights.tsx
Labels: Type: Non-breaking refactor

#925 [Bug] Fix out-of-sync behavior in agency dropdown menu
  common/components/Dropdown/Dropdown.tsx
Labels: Type: Bug

#924 [Publisher] Enable CSV download from Explore Data table view
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
  agency-dashboard/src/utils/index.ts
  common/utils/downloadHelpers.ts
  common/utils/index.ts
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/setupProxy.js
Labels: Type: Non-breaking refactor

#918 Agency Dashboard Refactor (Ramda + Chart Components)
  agency-dashboard/package.json
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/App.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  agency-dashboard/src/DashboardView/DashboardView.styles.tsx
  agency-dashboard/src/DashboardView/DashboardView.tsx
  agency-dashboard/src/DashboardView/index.ts
  agency-dashboard/src/Footer/Footer.tsx
  agency-dashboard/src/NotFound/NotFound.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/types.ts
  common/components/DataViz/utils.ts
  common/hooks/useBarChart.ts
  common/hooks/useLineChart.ts
  common/hooks/useLineChartLegend.ts
  common/package.json
  yarn.lock
Labels: Type: Non-breaking refactor

#927 Superagency: Playtesting Followup - UI adjustment for monthly records for superagencies with no configured metrics and only default annual metrics
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor

#926 add spinner while downloading custom spreadsheet
  publisher/public/assets/COURTS_AND_PRETRIAL.xlsx
  publisher/public/assets/COURTS_AND_PRETRIAL_SINGLE_PAGE.xlsx
  publisher/public/assets/DEFENSE.xlsx
  publisher/public/assets/DEFENSE_SINGLE_PAGE.xlsx
  publisher/public/assets/JAILS.xlsx
  publisher/public/assets/JAILS_SINGLE_PAGE.xlsx
  publisher/public/assets/LAW_ENFORCEMENT.xlsx
  publisher/public/assets/LAW_ENFORCEMENT_SINGLE_PAGE.xlsx
  publisher/public/assets/PRISONS.xlsx
  publisher/public/assets/PRISONS_SINGLE_PAGE.xlsx
  publisher/public/assets/PROSECUTION.xlsx
  publisher/public/assets/PROSECUTION_SINGLE_PAGE.xlsx
  publisher/public/assets/SUPERVISION.xlsx
  publisher/public/assets/SUPERVISION_SINGLE_PAGE.xlsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Feature

#935 [Publisher] Superagency: Playtesting Followups - Update copy and add banner to Records page
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/primitives/index.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#937 [Publisher] Correct REPORTING_PERIOD_CAPITALIZED constant to say "Recording Period" instead of "Reporting Period"
  publisher/src/components/Global/constants.ts
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#941 [Agency Dashboards] Remove agency from deny list
  agency-dashboard/src/utils/denylist.ts
Labels: Type: Non-breaking refactor

#943 [Agency Dashboards][Bug] Intermittent crash when hovering on charts
  agency-dashboard/src/utils/formatting.ts
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/types.ts
  common/hooks/useLineChartLegend.ts
Labels: Type: Bug

#956 update instructions for fiscal year
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Non-breaking refactor

#957 [Bug] Agency Dashboards: Handle undefined disaggregations when getting line chart data from metrics
  common/hooks/useLineChart.ts
Labels: Type: Bug

#940 [Publisher] Help Center: Routing + UI Scaffolding
  common/components/GlobalStyles/Palette.ts
  publisher/public/fonts/VitesseSSm-Light.otf
  publisher/public/index.css
  publisher/public/index.html
  publisher/src/App.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/HelpCenter/HelpCenter.tsx
  publisher/src/components/HelpCenter/HelpCenterBreadcrumbs.tsx
  publisher/src/components/HelpCenter/HelpCenterGuides.tsx
  publisher/src/components/HelpCenter/HelpCenterInterstitial.tsx
  publisher/src/components/HelpCenter/HelpCenterPublisher.tsx
  publisher/src/components/HelpCenter/index.ts
  publisher/src/stores/API.ts
Labels: Type: Feature

#955 Help Center: More Guides (in draft) + Centralized Guide Structure
  publisher/src/App.tsx
  publisher/src/components/HelpCenter/Guides/AccountSetupGuide.tsx
  publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/DashboardsGuide.tsx
  publisher/src/components/HelpCenter/Guides/ExploreDataGuide.tsx
  publisher/src/components/HelpCenter/Guides/ManualEntryGuide.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/Guides/TEMPLATE.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/HelpCenter/HelpCenterBreadcrumbs.tsx
  publisher/src/components/HelpCenter/HelpCenterDirectory.tsx
  publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx
  publisher/src/components/HelpCenter/HelpCenterInterstitial.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
  publisher/src/components/HelpCenter/README.md
  publisher/src/components/HelpCenter/index.ts
  publisher/src/components/HelpCenter/types.ts
Labels: Type: Non-breaking refactor

#961 Manual bump @babel/preset-env from 7.22.7 to 7.22.20
  common/package.json
  yarn.lock
Labels: Type: Dependency Upgrade

#977 [Agency Dashboards] Playtesting Followup - Add demo label under agency name and add agency name to category page
  agency-dashboard/src/AgencyOverview/AgencyOverview.styles.tsx
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
Labels: Type: Non-breaking refactor

#976 [Agency Dashboards] Playtesting Followup - Right align y-axis in bar chart
  common/components/DataViz/BarChartComponents.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
  common/components/DataViz/types.ts
Labels: Type: Non-breaking refactor

#974 [Agency Dashboards] Playtesting Followup - Hide individual breakdowns that have no value in Line Chart legend instead of showing "Not Recorded"
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
  common/components/DataViz/CategoryOverviewBreakdown.styles.tsx
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/types.ts
  common/hooks/useLineChartLegend.ts
Labels: Type: Non-breaking refactor

#962 Help Center: Styling Adjustments
  publisher/src/components/HelpCenter/Guides/AutomaticBulkUploadGuide.tsx
  publisher/src/components/HelpCenter/Guides/BulkUploadGuide.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
Labels: Type: Feature, Type: Non-breaking refactor

#972 Help Center: Home & Navigation
  common/components/GlobalStyles/Palette.ts
  publisher/src/App.tsx
  publisher/src/components/HelpCenter/HelpCenter.styles.tsx
  publisher/src/components/HelpCenter/HelpCenter.tsx
  publisher/src/components/HelpCenter/HelpCenterBreadcrumbs.tsx
  publisher/src/components/HelpCenter/HelpCenterDirectory.tsx
  publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx
  publisher/src/components/HelpCenter/HelpCenterInterstitial.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
  publisher/src/components/HelpCenter/README.md
  publisher/src/components/HelpCenter/index.ts
  publisher/src/components/HelpCenter/types.ts
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/assets/hc-agency-settings-icon.svg
  publisher/src/components/assets/hc-automated-bulk-upload-icon.svg
  publisher/src/components/assets/hc-bulk-upload-icon.svg
  publisher/src/components/assets/hc-dashboard-help-guide-thumbnail.png
  publisher/src/components/assets/hc-explore-your-data-icon.svg
  publisher/src/components/assets/hc-manual-entry-icon.svg
  publisher/src/components/assets/hc-publisher-help-guide-thumbnail.png
  publisher/src/components/assets/hc-set-up-metrics-icon.svg
  publisher/src/components/assets/hc-superagencies-icon.svg
  publisher/src/components/assets/hc-supervision-disaggregations-icon.svg
  publisher/src/components/assets/help-center-icon.svg
Labels: Type: Feature

#981 [Justice Counts] Small fixes to Bulk Upload Instructions page
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Non-breaking refactor

#980 [Agency Dashboards] Playtesting Followup - Filter charts by system in Category Overview page
  agency-dashboard/src/CategoryOverview/CategoryOverview.styled.tsx
  agency-dashboard/src/CategoryOverview/CategoryOverview.tsx
Labels: Type: Non-breaking refactor

#979 [Agency Dashboards] Playtesting Followup - Filter out datapoints with no aggregate values when rendering the line chart
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/hooks/useLineChart.ts
Labels: Type: Non-breaking refactor

#984 [Publisher] Help Center - Gate Help Center in menu until launch
  publisher/src/App.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor
