Repository Recidiviz/justice-counts, pull requests merged in 2023-06, with the labels that each got.

#660 Refactor bulk upload review page to handle and properly display multiple agency uploads
  common/components/DataViz/DatapointsTableView.styles.tsx
  common/components/DataViz/DatapointsTableView.tsx
  publisher/src/components/DataUpload/UploadReview.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/components/ReviewMetrics/types.ts
Labels: Type: Non-breaking refactor

#649 Adjustment to UploadReview logic to allow a super agency to publish for their child agencies
  common/components/DataViz/DatapointsTableView.styles.tsx
  common/components/DataViz/DatapointsTableView.tsx
  common/components/Modal/Modal.styled.tsx
  common/components/Modal/Modal.tsx
  common/types.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/UploadReview.tsx
  publisher/src/components/DataUpload/types.ts
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/components/ReviewMetrics/types.ts
Labels: Type: Non-breaking refactor

#686 Standalone version of bulk upload review page
  publisher/src/components/DataUpload/ShareSpreadsheet.tsx
  publisher/src/components/DataUpload/SpreadsheetReview.tsx
  publisher/src/components/DataUpload/UploadSpreadsheet.tsx
  publisher/src/mocks/spreadsheetReviewData.ts
  publisher/src/router/Router.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature

#707 [Justice Counts] Add Single Page Bulk Upload templates
  publisher/public/assets/COURTS_AND_PRETRIAL_SINGLE_PAGE.xlsx
  publisher/public/assets/DEFENSE_SINGLE_PAGE.xlsx
  publisher/public/assets/JAILS_SINGLE_PAGE.xlsx
  publisher/public/assets/LAW_ENFORCEMENT_SINGLE_PAGE.xlsx
  publisher/public/assets/PRISONS_SINGLE_PAGE.xlsx
  publisher/public/assets/PROSECUTION_SINGLE_PAGE.xlsx
  publisher/public/assets/SUPERVISION_SINGLE_PAGE.xlsx
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
Labels: Type: Non-breaking refactor

#720 Read only badge
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
Labels: Type: Non-breaking refactor

#711 Changes to race ethnicity disaggregation on data page
  common/components/DataViz/utils.ts
  common/stores/BaseDatapointsStore.ts
  common/types.ts
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
Labels: Type: Non-breaking refactor

#725 Gate the Delete functionality of Bulk Actions to JC Admins only
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#727 Nit#3: increase footer size
  publisher/src/components/Footer/Footer.styles.tsx
  publisher/src/components/Footer/Footer.tsx
  publisher/src/components/assets/footer-csg-logo.svg
Labels: Type: Non-breaking refactor

#726 Add state abbreviation next to agency name in Agencies dropdown
  publisher/src/components/Menu/Menu.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Non-breaking refactor

#722 Nit #2: update dropdown styling
  common/components/Button/Button.styled.tsx
  common/components/Button/Button.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/Reports/CreateReport.styled.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#721 Nit #1: changes to metric availability page
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#732 Nit #6: Metric Settings hover interaction
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
Labels: Type: Non-breaking refactor

#733 Nit #7: Change Save toast
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor

#737 [Justice Counts] Do not redefine SelectedFile on System Selection
  publisher/src/components/DataUpload/DataUpload.tsx
Labels: Type: Bug

#734 Nit #9: Change visual treatment for Agency Settings modal
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
Labels: Type: Non-breaking refactor

#738 Nit #10: Change heading on Data Entry page
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Reports/CreateReport.styled.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor

#736 Nit #11: Make headline for Data page bigger
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
Labels: Type: Non-breaking refactor
