Repository Recidiviz/justice-counts, pull requests merged in 2023-05, with the labels that each got.

#593 Metric Definitions page
  publisher/src/components/MetricSettings/DefinitionModalForm.styled.tsx
  publisher/src/components/MetricSettings/DefinitionModalForm.tsx
  publisher/src/components/MetricSettings/MetricConfig.tsx
  publisher/src/components/MetricSettings/MetricDefinitions.styled.tsx
  publisher/src/components/MetricSettings/MetricDefinitions.tsx
  publisher/src/components/MetricSettings/types.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#604 Remove description if no definitions
  publisher/src/components/MetricSettings/DefinitionModalForm.tsx
Labels: Type: Non-breaking refactor

#601 [Bug] Clicking on Data link while in the Data page does not reload the page
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Bug

#602 Bulk Upload: sanitize uploaded file name
  publisher/src/components/DataUpload/DataUpload.tsx
Labels: Type: Non-breaking refactor

#600 [Justice Counts] allowing bulk upload to accept csv files
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
Labels: Type: Feature

#612 [Justice Counts] change UploadButton to accept csv
  publisher/src/components/DataUpload/UploadFile.tsx
Labels: Type: Bug

#609 Shared header bar
  common/assets/jc-logo-vector-new.svg
  common/components/HeaderBar/HeaderBar.styled.tsx
  common/components/HeaderBar/HeaderBar.tsx
  common/components/HeaderBar/index.ts
  common/components/HeaderBar/types.ts
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmation.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.styles.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Non-breaking refactor

#605 Shared tabbed bar
  common/components/Button/Button.tsx
  common/components/Dropdown/Dropdown.tsx
  common/components/TabbedBar/TabbedBar.styled.tsx
  common/components/TabbedBar/TabbedBar.tsx
  common/components/TabbedBar/index.ts
  common/components/TabbedBar/types.ts
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Forms/NotReportedIcon.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#614 [Fix] Datapoint validation
  publisher/src/components/Reports/BulkActionReview.tsx
  publisher/src/components/Reports/DataEntryReview.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Bug

#613 Replace old metric settings with new ones
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/DataViz/types.ts
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/DimensionContexts.tsx
  publisher/src/components/MetricConfiguration/MetricBox.tsx
  publisher/src/components/MetricConfiguration/MetricBreakdownAvailabilityDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/MetricsConfiguration/Configuration.styled.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGridStates.ts
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
  publisher/src/components/MetricsConfiguration/constants.ts
  publisher/src/components/MetricsConfiguration/index.ts
  publisher/src/components/MetricsConfiguration/types.ts
  publisher/src/components/MetricsConfiguration/utils.ts
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/HelperText.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/pages/Settings.tsx
  publisher/src/router/Router.tsx
  publisher/src/stores/MetricConfigStore.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Non-breaking refactor

#622 Disable Guidance flow for all users
  publisher/src/components/Menu/Menu.tsx
  publisher/src/stores/GuidanceStore.ts
Labels: Type: Non-breaking refactor

#627 [Justice Counts] metric description bug fix
  publisher/src/components/MetricsConfiguration/Configuration.tsx
Labels: Type: Bug

#623 Metric Config: Hide "Show All" button for metrics that only have one breakdown
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#625 Metric Config: Render multiple includes-excludes descriptions
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#626 Bulk Upload: Render warnings (if any) for metrics that will not be uploaded
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Bug

#632 [Justice Counts] Metric Settings Copy Changes
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
Labels: Type: Non-breaking refactor

#636 [Justice Counts] Converting Annual to Annually in UI
  common/components/DataViz/DatapointsTitle.tsx
  common/utils/helperUtils.ts
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/utils/dateUtils.ts
Labels: Type: Non-breaking refactor

#629 [Fix] Restrict editing Supervision Populations to admins
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
Labels: Type: Bug

#646 [Justice Counts] Remove Courts Cases Overturned on Appeal from template
  publisher/public/assets/COURTS_AND_PRETRIAL.xlsx
Labels: Type: Non-breaking refactor

#642 Remove green floating "Available for data upload/publishing" box
  publisher/src/components/MetricsConfiguration/Configuration.tsx
Labels: Type: Non-breaking refactor

#641 Context values within includes/excludes should "count" as configuring
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
Labels: Type: Non-breaking refactor

#648 Metric Config: Replace checkmarks with toggles
  common/components/ToggleSwitch/ToggleSwitch.styles.tsx
  common/components/ToggleSwitch/ToggleSwitch.tsx
  common/components/ToggleSwitch/index.ts
  common/components/ToggleSwitch/types.ts
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Labels: Type: Non-breaking refactor

#654 Enable records bulk actions for agency admins
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#652 Quick Adjustment: Use toggles in definition modals and remove hover states
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.styled.tsx
Labels: Type: Non-breaking refactor

#665 Replace dropdown inside CreateReport
  common/components/Dropdown/Dropdown.styled.tsx
  publisher/src/components/Forms/Dropdown.tsx
  publisher/src/components/Reports/CreateReport.styled.tsx
  publisher/src/components/Reports/CreateReport.tsx
Labels: Type: Non-breaking refactor

#664 Header label and badge for overlay headers
  common/types.ts
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Header/hooks.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Bug

#663 Read only role for application
  common/components/RadioButton/RadioButton.styled.tsx
  common/components/RadioButton/RadioButtonsWrapper.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Header/hooks.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Feature

#679 Remove disaggregation pill if there is only one
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#674 Admin badge and tooltip adjustments
  common/components/Button/Button.styled.tsx
  common/components/Tooltip/Tooltip.styled.tsx
  common/components/Tooltip/index.ts
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/primitives/index.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#681 Fix sticky data entry form header
  publisher/src/components/Footer/Footer.styles.tsx
  publisher/src/components/Forms/Form.styles.tsx
Labels: Type: Non-breaking refactor

#685 Address unintiuitive behavior on Race/Ethnicity popup
  common/components/ToggleSwitch/ToggleSwitch.styles.tsx
  common/components/ToggleSwitch/ToggleSwitch.tsx
  common/components/ToggleSwitch/types.ts
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Labels: Type: Feature
