Repository Recidiviz/justice-counts, pull requests merged in 2023-02, with the labels that each got.

#348 Hook up editor badges to roles api
  common/types.ts
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/primitives/index.tsx
  publisher/src/mocks/reportOverviews.json
  publisher/src/pages/Reports.tsx
  publisher/src/stores/AgencyStore.ts
  publisher/src/stores/FormStore.test.tsx
Labels: Type: Feature

#359 [Fix] Add starting month selection for an annual metric
  publisher/src/components/MetricConfiguration/Configuration.tsx
Labels: Type: Non-breaking refactor

#361 [Fix] Adjust dimension box padding to prevent arrow overlap in long dimension names
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
Labels: Type: Non-breaking refactor

#360 [Fix] Add spacing between context items
  publisher/src/components/Forms/BinaryRadioButton.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
Labels: Type: Non-breaking refactor

#314 Guidance: Configure Metrics - Overview Screen & Computing Progress
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/types.ts
Labels: Type: Feature

#366 Add metric and dimension descriptions in the Metric Config settings
  common/types.ts
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#315 Remove initialization of entities from updater functions in metr…
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#367 Transition from auth0 permissions to roles
  common/types.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/DimensionContexts.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricContextConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/MetricConfiguration/RaceEthnicitiesForm.tsx
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/SettingsMenu.tsx
  publisher/src/pages/NotFound.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/router/Router.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Feature

#364 Small adjustments to the First Run Experience
  publisher/src/components/Onboarding/Onboarding.tsx
Labels: Type: Non-breaking refactor

#370 Fix initializing metric config values
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Bug

#376 Adjust ReportStore tests to reduce the run time to < 5s
  publisher/src/stores/ReportStore.test.tsx
Labels: Type: Bug

#371 Fix loader position (make more consistent) between different settings pages
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Loading/Loading.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/Settings/AgencySettings.tsx
Labels: Type: Non-breaking refactor

#385 [Fix] Replace EXCLUDED_SYSTEMS in Data Upload with SupervisionSubsystems
  common/types.ts
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Bug

#372 Update Supervision name to be "Supervision (Combined)" for supervision agencies with subsystems
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/Reports/PublishConfirmationSummaryPanel.tsx
  publisher/src/components/Reports/ReportSummaryPanel.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsBasicInfo.tsx
  publisher/src/utils/helperUtils.ts
Labels: Type: Non-breaking refactor

#384 new supervision template for bulk upload
  publisher/public/assets/SUPERVISION.xlsx
Labels: Type: Non-breaking refactor

#392 add logout button to the no agencies screen
  publisher/src/pages/NoAgencies.tsx
Labels: Type: Feature

#391 [Team Management] toast for error when user is already a part of an agency
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#373 Connect jurisdictions json to jurisdictions setting
  common/types.ts
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
Labels: Type: Feature

#398 [Justice Counts] fix: add new supervision template
  publisher/public/assets/SUPERVISION.xlsx
Labels: Type: Bug

#400 remove dual_supervision and post_release subsystems
  common/types.ts
  publisher/public/assets/SUPERVISION.xlsx
  publisher/src/utils/helperUtils.ts
Labels: Type: Non-breaking refactor

#406 Guidance: API
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/GuidanceHeader.tsx
  publisher/src/components/Guidance/types.ts
  publisher/src/stores/GuidanceStore.ts
Labels: Type: Feature

#427 [Bug] Resolve persistent error message in Reports overview page
  publisher/src/pages/Reports.tsx
Labels: Type: Bug

#430 Hotfix for jurisdictions to make a build
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
Labels: Type: Non-breaking refactor

#428 [Fix] Disaggregation and dimensions out of sync with the backend
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Bug

#429 Replace "system(s)" with "sector(s)"
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/SystemSelection.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Global/constants.ts
  publisher/src/components/MetricConfiguration/MetricConfiguration.tsx
  publisher/src/components/MetricConfiguration/MetricsView.tsx
  publisher/src/components/Settings/AgencySettingsBasicInfo.tsx
  publisher/src/mocks/mockReport.ts
  publisher/src/stores/AgencyStore.ts
Labels: Type: Non-breaking refactor

#417 Guidance (Follow Ups): Routing & Header
  publisher/src/App.tsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/GuidanceHeader.tsx
  publisher/src/components/Guidance/index.ts
  publisher/src/components/Guidance/types.ts
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/router/Router.tsx
  publisher/src/stores/GuidanceStore.ts
Labels: Type: Non-breaking refactor

#432 Guidance: Playtesting Followups - Breakdowns
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/MetricConfiguration/Configuration.tsx
  publisher/src/components/MetricConfiguration/MetricConfiguration.styles.tsx
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor

#443 Remove admin flag for displaying jurisdictions
  publisher/src/components/Settings/AgencySettings.tsx
Labels: Type: Non-breaking refactor

#447 Improve search algorithm for jurisdictions
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
Labels: Type: Non-breaking refactor

#448 [Justice Counts] new templates for Bulk Ipload based upon most recent TIGs
  publisher/public/assets/COURTS_AND_PRETRIAL.xlsx
  publisher/public/assets/DEFENSE.xlsx
  publisher/public/assets/JAILS.xlsx
  publisher/public/assets/LAW_ENFORCEMENT.xlsx
  publisher/public/assets/PRISONS.xlsx
  publisher/public/assets/PROSECUTION.xlsx
  publisher/public/assets/SUPERVISION.xlsx
Labels: Type: Non-breaking refactor

#444 Guidance: Support switching agencies
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/stores/GuidanceStore.test.tsx
  publisher/src/stores/GuidanceStore.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Non-breaking refactor
