Repository Recidiviz/justice-counts, pull requests merged in 2023-07, with the labels that each got.

#742 Refactor logic in definition modal form
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
Labels: Type: Non-breaking refactor

#730 New Homepage: Support agencies with multiple systems [2/n]
  publisher/src/components/Home/Home.styled.tsx
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/helpers.ts
  publisher/src/components/Home/types.ts
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Feature

#731 Agency Settings & Metric Config: Action Required treatment
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
Labels: Type: Feature

#751 New Homepage: Bug Fixes [6/n]
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/helpers.ts
  publisher/src/components/Home/types.ts
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/ReviewMetrics/helpers.ts
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature, Type: Bug

#745 Home Page: Link “Manual Entry” action link to Create Report page for users who do not have a records [5/n]
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/helpers.ts
  publisher/src/components/Home/types.ts
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/components/ReviewMetrics/helpers.ts
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature

#750 Make bar chart order same as legend from top to bottom
  common/components/DataViz/BarChart.tsx
Labels: Type: Non-breaking refactor

#753 Download chart
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/utils.ts
  publisher/package.json
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  yarn.lock
Labels: Type: Feature

#756 Remove Delete button in UploadedFiles
  publisher/src/components/DataUpload/UploadedFiles.tsx
Labels: Type: Non-breaking refactor

#757 [Bug] Fix checkmark bug in Record disaggregation tabs
  publisher/src/components/Forms/TabbedDisaggregations.tsx
Labels: Type: Bug

#752 New Homepage: P0 Mobile Responsiveness [7/n]
  common/components/Badge/Badge.tsx
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/GlobalStyles/Palette.ts
  common/components/HeaderBar/HeaderBar.styled.tsx
  common/components/HeaderBar/HeaderBar.tsx
  common/components/Toast/Toast.ts
  publisher/src/components/Auth/VerificationPage.tsx
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.styled.tsx
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/Footer/Footer.styles.tsx
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Header/Header.tsx
  publisher/src/components/Home/Home.styled.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Feature

#758 [Justice Counts] Connect FE to BE Standalone Bulk Upload Review Page
  publisher/src/components/DataUpload/ShareSpreadsheet.tsx
  publisher/src/components/DataUpload/SpreadsheetReview.tsx
  publisher/src/components/DataUpload/types.ts
  publisher/src/mocks/spreadsheetReviewData.ts
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature

#767 [Justice Counts] Connect FE to BE Standalone Bulk Upload Errors/Warnings Page
  publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Feature

#759 New Homepage: Playtesting Followups (P0)
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/helpers.ts
Labels: Type: Bug

#762 New Homepage: Playtesting Followups (P1)
  common/components/Tooltip/Tooltip.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Forms/TabbedDisaggregations.tsx
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/helpers.ts
  publisher/src/components/Reports/DataEntryReview.tsx
Labels: Type: Non-breaking refactor

#764 New Homepage: Deprecate all old Onboarding and Guidance
  common/components/Button/Button.styled.tsx
  publisher/src/components/Guidance/Guidance.styles.tsx
  publisher/src/components/Guidance/Guidance.tsx
  publisher/src/components/Guidance/index.ts
  publisher/src/components/Guidance/types.ts
  publisher/src/components/Onboarding/Onboarding.tsx
  publisher/src/components/Onboarding/OnboardingDataEntrySummary.tsx
  publisher/src/components/Onboarding/index.ts
  publisher/src/components/Reports/DataEntryForm.tsx
  publisher/src/pages/Reports.tsx
  publisher/src/stores/GuidanceStore.test.tsx
  publisher/src/stores/GuidanceStore.ts
  publisher/src/stores/RootStore.ts
  publisher/src/stores/UserStore.ts
Labels: Type: Non-breaking refactor

#765 New Homepage: Playtesting Followup - add helpful message to Create Records page when redirected from task card
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/Reports/CreateReport.styled.tsx
  publisher/src/components/Reports/CreateReport.tsx
Labels: Type: Feature

#768 New Homepage: Toast Adjustment
  common/components/Toast/Toast.ts
Labels: Type: Non-breaking refactor

#776 Add basic down-for-maintenance page
  publisher/src/components/Auth/Maintenance.tsx
Labels: Type: Feature

#766 [#21328] More Storybook stories
  common/components/DataViz/BarChart.stories.tsx
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/DatapointsTableView.stories.tsx
  common/components/DataViz/DatapointsTableView.styles.tsx
  common/components/DataViz/DatapointsTitle.stories.tsx
  common/components/DataViz/DatapointsTitle.styles.tsx
  common/components/DataViz/DatapointsView.stories.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/Legend.stories.tsx
  common/components/DataViz/Legend.tsx
  common/components/DataViz/MetricInsights.stories.tsx
  common/components/DataViz/MiniBarChart.stories.tsx
  common/components/DataViz/MobileFiltersModal.stories.tsx
  common/components/DataViz/MobileModal.styles.tsx
  common/components/DataViz/MobileSelectMetricsModal.stories.tsx
  common/components/DataViz/Tooltip.tsx
  common/components/MiniLoader/MiniLoader.stories.tsx
  common/components/Modal/Modal.stories.tsx
  common/components/Modal/Modal.styled.tsx
  common/components/Toast/Toast.stories.tsx
Labels: Type: Feature

#782 [#777] force reload on change dropdown selector event
  publisher/src/components/DataUpload/UploadedFiles.tsx
Labels: Type: Bug

#790 [Justice Counts] Standalone Errors/Warnings Page Close Fix
  publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
Labels: Type: Bug

#781 Update Delete button behavior in Uploaded Files page
  publisher/src/components/DataUpload/UploadedFiles.tsx
  publisher/src/components/Modals/types.ts
Labels: Type: Non-breaking refactor
