Repository Recidiviz/justice-counts, pull requests merged in 2023-11, with the labels that each got.

#1030 [Security] Auto-merge Dependabot minor and patch bumps
  .github/workflows/auto-merge-dependabot.yml
Labels: Type: Configuration Change

#1040 [Publisher] Remove duplicate state codes in agency name within the agency dropdown menu
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#1047 [Publisher] UI adjustment for creating fiscal year records
  publisher/src/components/Reports/CreateReport.tsx
Labels: Type: Non-breaking refactor

#1057 [Publisher] Admin Panel: Searchable List Component
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.tsx
  publisher/src/components/AdminPanel/InteractiveSearchList.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.test.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1068 [Bug] Fix link from Help Center to Agency Dashboards for production users
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Labels: Type: Bug
