Repository Recidiviz/justice-counts, pull requests merged in 2024-03, with the labels that each got.

#1187 [Publisher][Design Update][Metric Settings] Update layout of Metric Settings overview page (1/3)
  common/components/GlobalStyles/Typography.ts
  common/components/TabbedBar/TabbedBar.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
Labels: Type: Non-breaking refactor

#1188 [Publisher][Design Update][Metric Settings] Update layout of Metric Availability & Breakdowns page (2/3)
  common/components/Button/Button.styled.tsx
  common/components/CheckboxOptions/CheckboxOptions.styles.tsx
  common/components/CheckboxOptions/CheckboxOptions.tsx
  common/components/GlobalStyles/constants.ts
  common/components/RadioButton/RadioButton.tsx
  publisher/src/components/MetricsConfiguration/Configuration.styled.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Labels: Type: Non-breaking refactor

#1189 [Publisher][Design Update][Metric Settings] Update layout of Metric Definitions page (3/3)
  common/components/CheckboxOptions/CheckboxOptions.styles.tsx
  common/components/Input/Input.styled.tsx
  common/components/Input/Input.tsx
  common/components/Tooltip/Tooltip.styled.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
Labels: Type: Non-breaking refactor

#1215 [Publisher][Design Updates] Update Metric Settings Help Center guides
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
  publisher/src/components/assets/hc-set-up-metrics-definitions-screenshot.png
  publisher/src/components/assets/hc-set-up-metrics-page-screenshot.png
Labels: Type: Non-breaking refactor

#1223 [Justice Counts] un-gate emails subscription toggle for superagencies
  publisher/src/components/Settings/AgencySettings.tsx
Labels: Type: Non-breaking refactor

#1196 [Publisher][Design Updates] Update Supervision subpopulation layout and behavior in Metric Settings
  common/components/CheckboxOptions/CheckboxOptions.styles.tsx
  common/components/CheckboxOptions/CheckboxOptions.tsx
  common/components/TabbedBar/TabbedBar.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/Settings/utils.ts
Labels: Type: Non-breaking refactor

#1221 [Publisher] Metric Settings Design Updates
  common/components/Button/Button.styled.tsx
  common/components/CheckboxOptions/CheckboxOptions.styles.tsx
  common/components/CheckboxOptions/CheckboxOptions.tsx
  common/components/GlobalStyles/Typography.ts
  common/components/GlobalStyles/constants.ts
  common/components/Input/Input.styled.tsx
  common/components/Input/Input.tsx
  common/components/RadioButton/RadioButton.tsx
  common/components/TabbedBar/TabbedBar.styled.tsx
  common/components/Tooltip/Tooltip.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/HelpCenter/Guides/SetUpMetricsGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
  publisher/src/components/MetricsConfiguration/Configuration.styled.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/MetricsConfiguration/ModalForm.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.styled.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
  publisher/src/components/Settings/utils.ts
  publisher/src/components/assets/hc-set-up-metrics-definitions-screenshot.png
  publisher/src/components/assets/hc-set-up-metrics-page-screenshot.png
Labels: Type: Non-breaking refactor

#1224 [Publisher][Bug] Fix Help Center routing bug to allow relevant guides to link properly
  publisher/src/components/HelpCenter/HelpCenterGuideLayout.tsx
Labels: Type: Bug

#1227 [Publisher] Metric Settings - Adjust "Starting Month" section to read from `customOrDefaultFrequency` instead of `customFrequency`.
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#1225 [Publisher] Improve handling of `/users` PUT errors by displaying a generic error message
  publisher/src/App.tsx
  publisher/src/components/Loading/Loading.styles.tsx
  publisher/src/components/Loading/LoadingError.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Non-breaking refactor

#1239 [Publisher] Copy change on Enter Data page
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
Labels: Type: Non-breaking refactor

#1240 [Publisher] Add two download buttons to Explore Data page
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Non-breaking refactor

#1247 [Publisher] Metric Settings: Moves "Disaggregated by Supervision Type" tooltip copy to description body of "Metric Disaggregation"
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Non-breaking refactor

#1238 [Publisher] Agency Settings: Adds offset date picker for email notifications
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1237 [Publisher + Agency Dashboard] Data Charts: Display metric datapoints that match currently set frequency for each metric
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/types.ts
  common/components/DataViz/utils.ts
  common/stores/BaseDatapointsStore.ts
  common/types.ts
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/stores/DatapointsStore.ts
  publisher/src/stores/RootStore.ts
Labels: Type: Non-breaking refactor

#1253 [Publisher] Improve toggle experience for metrics page
  common/components/DataViz/DatapointsTableView.styles.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/GlobalStyles/constants.ts
  publisher/package.json
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  yarn.lock
Labels: Type: Non-breaking refactor

#1267 Revert "Bump @babel/preset-env from 7.22.20 to 7.24.3"
  common/package.json
  yarn.lock
Labels: Type: Bug

#1271 [Publisher]Agency Settings: edit profileDropdownMetadata and create GlobalStyles.tsx
  publisher/src/components/Global/GlobalStyles.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Breaking Change

#1273 [Justice Counts] ungate offset picker in production environment
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Labels: Type: Feature
