Repository Recidiviz/justice-counts, pull requests merged in 2024-06, with the labels that each got.

#1366 [Admin Panel] Add delete agency functionality
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1369 [Publisher] Option for unique search filter results w/ group headers
  common/components/Dropdown/Dropdown.tsx
  common/components/Dropdown/types.ts
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
Labels: Type: Non-breaking refactor

#1376 Revert "Bump @babel/preset-react from 7.24.1 to 7.24.7"
  common/package.json
  yarn.lock
Labels: Type: Bug

#1380 Exclude @babel packages from dependabot auto-merge
  .github/workflows/auto-merge-dependabot.yml
Labels: Type: Non-breaking refactor

#1378 [Publisher] Persist current metric after switching to a different child agency via the dropdown
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
Labels: Type: Feature

#1390 [Publisher] Copy update in confirmation modal after publishing and swap positions of "View Data" and "Go to Records" buttons
  publisher/src/components/DataUpload/SpreadsheetReview.tsx
  publisher/src/components/Reports/BulkActionReview.tsx
  publisher/src/components/Reports/DataEntryReview.tsx
  publisher/src/components/Reports/constants.ts
  publisher/src/components/ReviewMetrics/helpers.ts
Labels: Type: Non-breaking refactor

#1389 [Publisher] Add agency name and CY/FY suffix to record names in the publish review existing records warning message
  common/utils/dateUtils.ts
  publisher/src/components/DataUpload/DataUpload.styles.tsx
  publisher/src/components/DataUpload/SpreadsheetReview.tsx
  publisher/src/components/DataUpload/UploadSpreadsheet.tsx
  publisher/src/stores/HomeStore.ts
Labels: Type: Non-breaking refactor

#1408 [Publisher] Keep chart calculation regardless of screen width
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
Labels: Type: Non-breaking refactor
