Repository Recidiviz/justice-counts, pull requests merged in 2024-07, with the labels that each got.

#1407 [Publisher][Superagencies] Add filters to Home page table
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/package.json
  publisher/src/components/Home/ChildAgenciesTable.styled.tsx
  publisher/src/components/Home/ChildAgenciesTable.tsx
  publisher/src/components/Home/EditModal.tsx
  publisher/src/components/Home/Home.test.tsx
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/SystemsCheckboxDropdown.styled.tsx
  publisher/src/components/Home/SystemsCheckboxDropdown.tsx
  publisher/src/components/Home/TableSearchInput.styled.tsx
  publisher/src/components/Home/TableSearchInput.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
  publisher/src/stores/AdminPanelStore.ts
  publisher/src/stores/HomeStore.ts
  yarn.lock
Labels: Type: Feature

#1419 [Publisher] Add Agency Name to Data Download CSV
  common/utils/downloadHelpers.ts
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Configuration Change

#1421 [Publisher] refetch agencies every time that they are edited in the admin panel
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1425 [Publisher] Update team members tab in agency settings
  common/components/Input/Input.styled.tsx
  common/types.ts
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsTeamManagement.tsx
  publisher/src/components/Settings/Settings.styles.tsx
Labels: Type: Non-breaking refactor

#1422 [Publisher] Allow users to select starting month when creating an annual record
  publisher/src/components/Reports/CreateReport.styled.tsx
  publisher/src/components/Reports/CreateReport.tsx
  publisher/src/utils/dateUtils.ts
Labels: Type: Non-breaking refactor

#1410 [Publisher] Remove autosave before exit in records
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor

#1432 [Publisher][Design Updates] Update Enter Data homepage layout
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.styled.tsx
  publisher/src/components/DataEntryInterstitial/DataEntryInterstitial.tsx
Labels: Type: Non-breaking refactor

#1436 [Publisher] Fix Download Data downloading blank CSVs in Explore Data page
  common/utils/downloadHelpers.ts
Labels: Type: Bug

#1433 [Publisher][Design Updates] Update Records overview page layout
  common/components/Button/Button.styled.tsx
  common/components/Modal/Modal.styled.tsx
  common/components/Modal/Modal.tsx
  common/components/TabbedBar/TabbedBar.styled.tsx
  publisher/src/components/Modals/UnauthorizedDeleteActionModal.tsx
  publisher/src/components/Reports/BulkActionReview.tsx
  publisher/src/components/Reports/Reports.styles.tsx
  publisher/src/components/Reports/constants.ts
  publisher/src/components/ReviewMetrics/helpers.ts
  publisher/src/pages/Reports.tsx
  publisher/src/utils/dateUtils.ts
Labels: Type: Non-breaking refactor

#1434 [Publisher][Admin Panel] Add scroll to top button in overview pages
  common/components/ScrollToTop/ScrollToTop.tsx
  common/components/ScrollToTop/index.ts
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
Labels: Type: Feature

#1409 [Publisher] Update Explore Data page to allow toggle between metric reporting frequencies
  agency-dashboard/src/stores/AgencyDataStore.ts
  common/components/DataViz/DatapointsView.stories.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/DataViz/DatapointsView.tsx
  common/components/DataViz/Legend.tsx
  common/components/DataViz/MobileFiltersModal.stories.tsx
  common/components/DataViz/utils.test.ts
  common/components/DataViz/utils.ts
  common/hooks/useBarChart.ts
  common/stores/DataVizStore.ts
  common/types.ts
  publisher/src/components/DataViz/ConnectedDatapointsView.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Feature, Type: Non-breaking refactor

#1443 [Agency Dashboard] Remove slug from published data url for agency dashboards
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
Labels: Type: Non-breaking refactor

#1451 [Bug Bash][Common] Fix react/no-unstable-nested-components lint errors
  common/components/DataViz/BarChart.tsx
  common/components/DataViz/MetricsCategoryBarChart.tsx
Labels: Type: Non-breaking refactor
