Repository Recidiviz/justice-counts, pull requests merged in 2024-01, with the labels that each got.

#1126 [Publisher] Admin Panel: Quick bug fix with link to Live Dashboard
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Labels: Type: Bug

#1125 toggle in agency settings to turn unsubscribe / subscribe to email
  common/components/ToggleSwitch/ToggleSwitch.styles.tsx
  common/components/ToggleSwitch/ToggleSwitch.tsx
  common/components/ToggleSwitch/types.ts
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1130 [Justice Counts] update task cards for uploading missing metrics
  publisher/src/components/Home/Home.test.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/types.ts
  publisher/src/stores/HomeStore.test.tsx
  publisher/src/stores/HomeStore.ts
Labels: Type: Feature

#1134 [Publisher] Admin Panel: CSG Followups - Ensure supervision subpopulation sectors cannot be selected without Supervision sector also being selected
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Non-breaking refactor

#1136 [Publisher][Bug] Admin Panel: Exclude superagency sector from consideration when determining whether or not a user has sectors selected
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Bug, Type: Non-breaking refactor

#1137 [Publisher] Admin Panel: CSG Followups - Add link to Publisher in agency cards
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Labels: Type: Non-breaking refactor

#1133 [Publisher][Bug] Fix superagency double upload bugs by removing special filtering in `UploadFile` component
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/UploadFile.tsx
Labels: Type: Bug

#1142 [Agency Dashboards] Hide disabled metrics
  agency-dashboard/src/stores/AgencyDataStore.ts
Labels: Type: Non-breaking refactor

#1139 [Agency Dashboard] Adjust the displayed year for Fiscal Year datapoints to be the datapoint end year and not the start year for the data charts
  common/components/DataViz/CategoryOverviewBreakdown.tsx
  common/components/DataViz/CategoryOverviewLineChart.tsx
  common/components/DataViz/utils.test.ts
  common/components/DataViz/utils.ts
Labels: Type: Non-breaking refactor

#1143 [Publisher] Group non-calendar year records under the year that matches their end year
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#1151 [Publisher] Rename Bulk Upload 'example(s)' to 'template(s)'
  publisher/src/components/DataUpload/InstructionsTemplate.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
Labels: Type: Non-breaking refactor

#1150 [Publisher][Bug] Fix encoding of agency names when linking to dashboards
  agency-dashboard/src/Home/Home.tsx
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
Labels: Type: Bug

#1153 [Justice Counts] Add a GH action to trigger playtesting deployment from frontend PRs.
  .github/workflows/deploy_to_playtesting.yml
Labels: Type: Feature

#1157 [Justice Counts] update toggle copy and access
  common/types.ts
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/components/Settings/AgencySettings.tsx
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Labels: Type: Feature

#1158 [Justice Counts] add toast to confirm that email settings were updated
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1154 [Publisher] Admin Panel: Add functionality for deleting users
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/assets/icons8-trash.svg
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1149 [Publisher] Admin Panel: Add a FE trigger for the copying of superagency metric settings to child agencies process in the UI
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1164 [Justice Counts] Tag actor and add failure message for playtest deployment.
  .github/workflows/deploy_to_playtesting.yml
Labels: Type: Feature

#1173 [Justice Counts] Update toggle copy to describe emails
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Labels: Type: Non-breaking refactor

#1174 [Publisher] Temporarily silencing Sentry
  publisher/src/components/Auth/AuthStore.ts
  publisher/src/index.tsx
Labels: Type: Non-breaking refactor

#1176 [Publisher] Add agency name header when viewing a record
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/HeaderBar/HeaderBar.styled.tsx
  publisher/src/components/Menu/Menu.styles.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor
