Repository Recidiviz/justice-counts, pull requests merged in 2024-09, with the labels that each got.

#1486 [Publisher] Add total number to breakdown tooltip
  common/components/DataViz/Tooltip.tsx
Labels: Type: Feature

#1487 [Publisher] Remove Disabled Metric Message and Show Warning in Alerts When Showing Supervision Sheet Errors
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
  publisher/src/components/DataUpload/UploadErrorsWarnings.tsx
  publisher/src/components/DataUpload/utils.ts
Labels: Type: Feature

#1497 [Publisher] Update breakdown view behavior on Explore Data page
  common/components/DataViz/DatapointsView.tsx
Labels: Type: Bug, Type: Configuration Change

#1498 [Publisher][Bug] Explore Data: Breakdowns show missing data
  common/stores/BaseDatapointsStore.ts
Labels: Type: Bug

#1508 [Publisher] Don't filter out 0 values in `Review Data` page
  publisher/src/components/DataUpload/SpreadsheetReview.tsx
  publisher/src/stores/ReportStore.ts
Labels: Type: Bug

#1509 [Agency Dashboard] Upgrades for vulnerable transitive packages
  agency-dashboard/package.json
  yarn.lock
Labels: Type: Non-breaking refactor

#1520 [Publisher] Fix "edit you account" typo.
  publisher/src/pages/Settings.tsx
Labels: Type: Bug

#1511 [Publisher] Only query an agency if the user visits that agency's page.
  common/types.ts
  publisher/src/components/Home/Home.test.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/Reports/CreateReport.test.tsx
  publisher/src/router/Router.tsx
  publisher/src/stores/HomeStore.test.tsx
  publisher/src/stores/UserStore.ts
Labels: Type: Feature, Type: Enhancement
