Repository Recidiviz/justice-counts, pull requests merged in 2024-05, with the labels that each got.

#1319 [Justice Counts] Trim whitespace from agency name
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1320 [Publisher][Bug] Set Up Metrics Overview Page: Fix grouping of action required, available, and unavailable for supervision agencies with subpopulations
  common/utils/helperUtils.ts
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/MetricsConfiguration/types.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Bug

#1282 [Publisher][Admin Panel] Add functionality to choose metrics/child agencies during metric copy
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/components/assets/close-icon.svg
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1331 [Justice Counts] Replace curly with straight apostrophe in agency name
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Non-breaking refactor

#1327 [Publisher][Design Update] Agency Settings: Account Tab Modals (excluding Jurisdictions) (3/5) #1257
  common/components/Button/Button.styled.tsx
  common/components/Button/Button.tsx
  common/components/Input/Input.styled.tsx
  common/components/Input/Input.tsx
  common/components/Modal/Modal.styled.tsx
  common/components/Modal/Modal.tsx
  common/utils/helperUtils.ts
  publisher/src/components/Settings/AccountSettings.styles.tsx
  publisher/src/components/Settings/AccountSettings.tsx
  publisher/src/components/Settings/AgencySettings.styles.tsx
  publisher/src/components/Settings/AgencySettingsDescription.tsx
  publisher/src/components/Settings/AgencySettingsEditModeModal.tsx
  publisher/src/components/Settings/AgencySettingsJurisdictions.tsx
  publisher/src/components/Settings/AgencySettingsSupervisions.tsx
  publisher/src/components/Settings/AgencySettingsURL.tsx
Labels: Type: Breaking Change

#1338 [Publisher] Update Help Center Guide for New Settings Page
  publisher/src/components/HelpCenter/Guides/SettingsGuide.tsx
  publisher/src/components/HelpCenter/Guides/SupervisionDisaggregationGuide.tsx
  publisher/src/components/HelpCenter/HelpCenterSetup.tsx
  publisher/src/components/HelpCenter/types.ts
  publisher/src/components/Home/Home.tsx
  publisher/src/components/assets/hc-agency-settings-jurisdiction-screenshot.png
  publisher/src/components/assets/hc-agency-settings-page-screenshot.png
  publisher/src/components/assets/hc-settings-page-screenshot.png
  publisher/src/pages/Settings.tsx
Labels: Type: Non-breaking refactor

#1339 [Publisher] Disable Supervision Subpopulation checkboxes in Metric Settings for READ ONLY users
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
Labels: Type: Bug, Type: Non-breaking refactor

#1340 [Agency Dashboards] Adjust "records" to record when there is only one published record
  agency-dashboard/src/Home/Home.tsx
Labels: Type: Non-breaking refactor

#1343 [Publisher][Bug] Fix link to Uploaded Files
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/Settings/AccountSettings.styles.tsx
  publisher/src/router/Router.tsx
Labels: Type: Bug

#1347 [Publisher] Agency Settings - Ungate email reminders to production users
  publisher/src/components/Settings/AgencySettingsEmailNotifications.tsx
Labels: Type: Non-breaking refactor

#1341 [Publisher][Bug] Remove additional context logic from FormStore and DataEntryFormComponents
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/components/Reports/DataEntryFormComponents.tsx
  publisher/src/stores/FormStore.test.tsx
  publisher/src/stores/FormStore.ts
Labels: Type: Bug

#1351 [Publisher][Bug] Fix metric definitions display for agencies with supervision + other non-supervision sectors
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
Labels: Type: Bug
