Repository Recidiviz/justice-counts, pull requests merged in 2024-04, with the labels that each got.

#1269 [Publisher][Admin Panel] Auto-add users/agencies created via second flow
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/UserProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1293 [Justice Counts][Temp Bug Fix] Handle undefined case in FormStore `validate` logic
  publisher/src/stores/FormStore.ts
Labels: Type: Bug

#1285 [Justice Counts] Update dashboard URLs to have agencyID
  agency-dashboard/src/App.tsx
  agency-dashboard/src/Home/Home.tsx
  agency-dashboard/src/Protected/Protected.tsx
  agency-dashboard/src/stores/AgencyDataStore.ts
  publisher/src/components/HelpCenter/LinkToPublisherDashboard.tsx
  publisher/src/components/Menu/Menu.tsx
Labels: Type: Non-breaking refactor

#1286 [Publisher][Admin Panel] Add functionality to select all filtered items from InteractiveSearchList
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/InteractiveSearchList.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/components/AdminPanel/types.ts
Labels: Type: Feature

#1294 [Publisher][Superagencies] Save new child agencies data in AgencyStore
  common/types.ts
  publisher/src/components/Home/types.ts
  publisher/src/components/Menu/Menu.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1295 [Publisher][Superagencies] Add dropdown for child agencies to Set Up Metrics page
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1310 [Publisher][Superagencies] Add dropdown for child agencies to Explore Data page
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.styled.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
Labels: Type: Feature

#1311 [Agency Dashboard][Bug] Fix linking to Category Overview page
  agency-dashboard/src/AgencyOverview/AgencyOverview.tsx
Labels: Type: Bug

#1313 Revert "[Publisher][Superagencies] Add dropdown for child agencies to Set Up Metrics page"
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Bug

#1314 [Publisher][Superagencies] Add dropdown for child agencies
  common/components/Dropdown/Dropdown.styled.tsx
  common/components/Dropdown/Dropdown.tsx
  publisher/src/components/DataViz/MetricsDataChart.styled.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/Menu/Menu.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.styled.tsx
  publisher/src/components/MetricsConfiguration/ChildAgenciesDropdown.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.styled.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature
