Repository Recidiviz/justice-counts, pull requests merged in 2024-10, with the labels that each got.

#1529 [Publisher][Bug] Alternate Solution: Fix bug where adding team members to the admin panel clears out all other team members
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Bug

#1536 [Publisher][Admin Panel] Add preload spinner to admin panel modals
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1544 [Publisher][Admin Panel][Bug] Fix admin panel loader
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Bug

#1541 [Publisher] Agency Settings - Add new agency-wide Courts + Supervision Subpopulation TIG elements
  publisher/src/components/AgencySettings/AccountSettings.styles.tsx
  publisher/src/components/AgencySettings/AccountSettings.tsx
  publisher/src/components/AgencySettings/AgencySettings.styles.tsx
  publisher/src/components/AgencySettings/AgencySettings.tsx
  publisher/src/components/AgencySettings/AgencySettingsBasicInfo.tsx
  publisher/src/components/AgencySettings/AgencySettingsDescription.tsx
  publisher/src/components/AgencySettings/AgencySettingsEditModeModal.tsx
  publisher/src/components/AgencySettings/AgencySettingsEmailNotifications.tsx
  publisher/src/components/AgencySettings/AgencySettingsJurisdictions.tsx
  publisher/src/components/AgencySettings/AgencySettingsSupervisions.tsx
  publisher/src/components/AgencySettings/AgencySettingsTeamManagement.tsx
  publisher/src/components/AgencySettings/AgencySettingsURL.tsx
  publisher/src/components/AgencySettings/IncludesExcludes/includesExcludes.ts
  publisher/src/components/AgencySettings/IncludesExcludes/types.ts
  publisher/src/components/AgencySettings/Settings.styles.tsx
  publisher/src/components/AgencySettings/TabContent.tsx
  publisher/src/components/AgencySettings/hooks.ts
  publisher/src/components/AgencySettings/index.ts
  publisher/src/components/AgencySettings/types.ts
  publisher/src/components/AgencySettings/utils.ts
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/Configuration.tsx
  publisher/src/components/MetricsConfiguration/MetricAvailability.tsx
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/MetricsConfiguration/MetricsOverview.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesGrid.tsx
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
  publisher/src/pages/Settings.tsx
  publisher/src/stores/AgencyStore.ts
Labels: Type: Feature

#1552 [Publisher] Sort records list by year and month in review metrics page
  common/utils/dateUtils.ts
  publisher/src/components/ReviewMetrics/ReviewMetrics.tsx
Labels: Type: Configuration Change

#1559 [Publisher][Admin Panel] Add modal loader unit tests
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
Labels: Type: Configuration Change

#1543 [Publisher][Admin Panel] Add team members search bar & sort them alphabetically
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Feature
