Repository Recidiviz/justice-counts, pull requests merged in 2025-01, with the labels that each got.

#1628 [Publisher][Bug] Fix bug where Explore Data page shows first Combined Supervision datapoints when Supervision sector is disaggregated
  publisher/src/components/DataViz/MetricsDataChart.tsx
Labels: Type: Bug

#1638 [Publisher] Fix enabled dimension leaking from another sectors
  common/components/DataViz/utils.ts
Labels: Type: Bug

#1557 [Publisher] Add "Other" textbox to race breakdown
  common/types.ts
  publisher/src/components/MetricsConfiguration/RaceEthnicitiesModalForm.tsx
  publisher/src/components/MetricsConfiguration/types.ts
  publisher/src/stores/MetricConfigStore.tsx
Labels: Type: Feature

#1640 [Justice Counts] Remove Unknown County Fips
  publisher/src/components/AdminPanel/types.ts
Labels: Type: Bug

#1639 [Publisher] Fix "Other" checking and unchecking behavior in Metric Settings
  publisher/src/components/MetricsConfiguration/DefinitionModalForm.tsx
Labels: Type: Bug

#1653 [Publisher][Admin Panel] Remove "Copy metric settings to child agencies" feature from new agency flow
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
Labels: Type: Bug, Type: Configuration Change

#1655 [Publisher] Gate create records route from non-admins
  publisher/src/components/Home/Home.styled.tsx
  publisher/src/components/Home/Home.tsx
  publisher/src/components/Home/TaskCard.tsx
  publisher/src/components/Home/types.ts
Labels: Type: Configuration Change
