Repository Recidiviz/justice-counts, pull requests merged in 2025-04, with the labels that each got.

#1718 Update CI node version
  .github/workflows/ci.yml
  agency-dashboard/package.json
  common/package.json
  publisher/package.json
Labels: Type: Configuration Change

#1712 [Publisher] Data Entry: Update empty record state
  publisher/src/components/Forms/Form.styles.tsx
  publisher/src/components/Reports/DataEntryForm.tsx
Labels: Type: Non-breaking refactor

#1722 [Publisher] Update loading error
  publisher/src/components/DataUpload/ShareSpreadsheet.tsx
  publisher/src/components/DataUpload/ShareUploadErrorWarnings.tsx
  publisher/src/components/DataViz/MetricsDataChart.tsx
  publisher/src/components/MetricsConfiguration/MetricsConfiguration.tsx
  publisher/src/components/Reports/BulkActionReview.tsx
  publisher/src/components/Reports/DataEntryForm.test.tsx
  publisher/src/components/Reports/ReportDataEntry.tsx
  publisher/src/pages/Reports.tsx
Labels: Type: Non-breaking refactor

#1729 [Publisher][Bug] Admin Panel: Disable create new agency secondary flow
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/UserProvisioning.tsx
Labels: Type: Bug

#1737 [Publisher] Update Copy for Stepping Up Context Questions
  publisher/src/components/AgencySettings/SteppingUpContextualInformation.tsx
Labels: Type: Non-breaking refactor

#1741 [Publisher] Fixed metrics definition crash in jails agency
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
Labels: Type: Bug

#1742 [Publisher][Bug] Fix crash when attempting to go to non provisioned agency
  publisher/src/components/Menu/Menu.tsx
  publisher/src/router/Router.tsx
Labels: Type: Bug

#1734 [Publisher] Add Custom Other Configuration in Admin Panel
  common/components/DataViz/DatapointsTableView.tsx
  common/components/TabbedBar/TabbedBar.styled.tsx
  common/components/TabbedBar/TabbedBar.tsx
  common/hooks/index.ts
  common/hooks/useScrollShadows.ts
  publisher/src/components/AdminPanel/AdminPanel.styles.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningComponents/BreakdownSettings.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningComponents/index.ts
  publisher/src/components/AdminPanel/AgencyProvisioningContext.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature
