Repository Recidiviz/justice-counts, pull requests merged in 2025-03, with the labels that each got.

#1693 Update CI workflow actions/cache version to v4
  .github/workflows/ci.yml
Labels: Type: Configuration Change

#1682 [Publisher] Add frequency indicators to the data table
  common/components/DataViz/DatapointsTableView.styles.tsx
  common/components/DataViz/DatapointsTableView.tsx
  common/components/DataViz/DatapointsView.styles.tsx
  common/components/GlobalStyles/Typography.ts
Labels: Type: Feature

#1694 [Publisher][Bug] Fix app crash when missing Metric Definitions
  publisher/src/components/MetricsConfiguration/MetricDefinitions.tsx
Labels: Type: Bug

#1691 [Publisher] Add Datapoints Shared column to Uploaded Files table
  publisher/src/components/DataUpload/DataUpload.tsx
  publisher/src/components/DataUpload/UploadedFiles.styles.tsx
  publisher/src/components/DataUpload/UploadedFiles.tsx
Labels: Type: Feature

#1702 [Publisher] Add "Stepping Up Agency" Checkbox to Agency Modal
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/AgencyProvisioning.tsx
  publisher/src/components/AdminPanel/AgencyProvisioningOverview.tsx
  publisher/src/components/AdminPanel/types.ts
  publisher/src/stores/AdminPanelStore.test.tsx
  publisher/src/stores/AdminPanelStore.ts
Labels: Type: Feature

#1703 [Publisher][Admin Panel] Add more unit tests for Admin Panel
  publisher/src/components/AdminPanel/AdminPanel.test.tsx
  publisher/src/components/AdminPanel/VendorManagementModal.tsx
  publisher/src/stores/AdminPanelStore.test.tsx
Labels: Type: Configuration Change
